### ISSUE TITLE
Unable to Update DOI via form

### ISSUE THREAD

**Issue by zcc39r** [datacite/bracco#116]
After the update attempt Creator and Title fields become filled with bracketed objects. Nothing happens with metadata.

![beforeupdate](https://user-images.githubusercontent.com/17593292/50482356-2bec7680-09f7-11e9-864b-ab4c4bb4ec34.jpg)
![afterupdate](https://user-images.githubusercontent.com/17593292/50482365-31e25780-09f7-11e9-847d-2e194f308f0d.jpg)

<img src="https://frontapp.com/assets/img/icons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_gf7v)

**Comment by richardhallett** [comment]
This should have been fixed as part of our latest Form fixes on Fabrica. See https://github.com/datacite/datacite/issues/610 for more information.

However if there is still an inability to post a DOI it might be a separate validation issue.
Please let us know if you still have a problem for specific DOI's with our main support channel support@datacite.org

**Comment by richardhallett** [comment]
Please see my reply to your specific usecase sent yo your email.

But for the purposes of the bug, there was some fixes deployed around validation of title/description which I believe was the original cause of this not being able to be updated.
