### ISSUE TITLE
TypeError in Clients show dois show (clients.show.dois.show.index, /clients/subgoe.herder/dois/10.25626%2F0004)

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#123]
## Error in DOI Fabrica

**TypeError** in **Clients show dois show (clients.show.dois.show.index, /clients/subgoe.herder/dois/10.25626%2F0004)**
e.map is not a function

[View on Bugsnag](https://app.bugsnag.com/datacite/doi-fabrica/errors/5c2caab9ee587d001ad9fb68?event_id=5c2caad30032017c538c0000&i=gh&m=ci)

## Stacktrace

    bracco/routes/clients/show/dois/show/edit.js:32 - creatorsToSeperated
    bracco/routes/clients/show/dois/show/edit.js:28 - afterModel

[View full stacktrace](https://app.bugsnag.com/datacite/doi-fabrica/errors/5c2caab9ee587d001ad9fb68?event_id=5c2caad30032017c538c0000&i=gh&m=ci)

*Created by Martin Fenner via Bugsnag*

**Comment by richardhallett** [comment]
This bug was related to how the creators field was being handled, see notes on https://github.com/datacite/datacite/issues/610
