### ISSUE TITLE
Show the URL from the DB not handle system

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#138]
Originally there was some situations where the DB did not have the URL registered in the handle system, so fabrica showed the URL from handle system.

Now it would be better to show the one from the DB.

The user issue here is that it can cause confusion about what is actually the updated URL. e.g. sometimes if you change the URL it looks in fabrica like it didn't actually update

**Comment by mfenner** [comment]
This has been resolved in bracco 3.3.
