### ISSUE TITLE
Tests for Fabrica form

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#140]
Write integration tests and acceptance tests for the Fabrica DOI registration form.

* https://guides.emberjs.com/release/testing/testing-components/
* https://guides.emberjs.com/release/testing/acceptance/

Use existing tests as a starting point, in particular for authentication with different roles, e.g. https://github.com/datacite/bracco/blob/master/tests/acceptance/client_admin/client-test.js.

The tests should cover the following:

* allowed value
* multiple values
* missing value
* incorrect value(s)
* insufficient permissions
* adding/editing/deleting of values

**Comment by kjgarza** [comment]
In other words we need to implement:

*Rendering Tests* for components:

- publicationYear, doi-form.hbs
- publisher,  doi-form.hbs
- doi fields, doi-doi.hbs
- titles, doi-titles.hbs
- description, doi-description.hbs
- creators,  doi-creator.hbs


*Acceptace/application* tests for:

- When logged as a Providerv isiting my own existing  DOI
- When logged as a Client visiting an other clients DOI
	- the form should not render.
- When logged as a Client and visiting my own existing findabale DOI
	- the form should render
	- the xml metadata should be reflected in the form.
	- URL should be rendered
	- I should not be able to make the DOI draft
	- I should be able to make the DOI registered
	- I shoudl not be able to save after removing the URL
	- I should not be able to save after removing  mandatory field
	- I should be able to edit all/any fields and save
	- I should not be able to edit the DOI name
- When logged as a Client and visiting my own existing registered DOI
	- the form should render
	- the xml metadata should be reflected in the form.
	- I should not be able to make the DOI draft
	- I should be able to make the DOI findable
	- I shoudl not be able to save after removing the URL
	- I should not be able to save after removing  mandatory field
	- I should be able to edit all/any fields and save
	- I should not be able to edit the DOI name
- When logged as a Client and visiting my own existing draft DOI
	- the form should render
	- the xml metadata should be reflected in the form.
	- I should be able to make the DOI findable
	- I should be able to make the DOI registered
	- I should be able to make the DOI draft
	- I should be able to edit all/any fields and save
	- I should be able to edit the DOI name

**Comment by kjgarza** [comment]
- To focus mostly on acceptance tests.
- To Put aside the individual components tests
- To Focus on acceptance test that deal with multiple creator, titles and descriptions.

**Comment by kjgarza** [comment]
I have limited the acceptance test two 2 two cases now:

Acceptance Test

- When logged as a Client and visiting my own existing findable DOI
	- the form should render
	- the xml metadata should be reflected in the form.
	- multiple titles, creators, and descriptions should be rendered separately
        - I should be able to add and edit Publication year and publisher
	- I should be able to remove, add, & edit multiple titles
	- I should be able to remove, add, & edit multiple descriptions
	- I should be able to remove, add, & edit multiple creators
- When logged as a Client and try to create a new DOI
	- the form should render
        - I should be able to add and edit Publication year and publisher
	- I should be able to remove, add, & edit multiple titles
	- I should be able to remove, add, & edit multipledescriptions
	- I should be able to remove, add, & edit multiple creators

If there are further comments, please let me know

**Comment by kjgarza** [comment]
Three issues affecting validations that are affecting the tests in here:

- https://usersnap.com/a/#/datacite/p/datacite-41ebcc0f/566
- https://usersnap.com/a/#/datacite/p/datacite-41ebcc0f/565
- https://usersnap.com/a/#/datacite/p/datacite-41ebcc0f/564
