### ISSUE TITLE
Tests for publisher form field

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#142]
Child of #140.

**Comment by kjgarza** [comment]
allowed value 73fb618e20a0e85a4ec1e55be68d3217af500ae0
multiple values N/A
missing value a261d08aa2a75d648fdc2b853a7388474e9f2fdd
incorrect value(s) a261d08aa2a75d648fdc2b853a7388474e9f2fdd
insufficient permissions N/A
adding/editing/deleting of values in c52107fa840f9da966960490c4dd057f66fb6c3c
