### ISSUE TITLE
Tests for DOI form fields (prefix and suffix)

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#143]
Child of #140.

**Comment by kjgarza** [comment]
allowed value 73fb618e20a0e85a4ec1e55be68d3217af500ae0
multiple values N/A
missing value  664bcfc8fbf77e926c3cb93e75e592c162e61792
incorrect value(s)  664bcfc8fbf77e926c3cb93e75e592c162e61792
insufficient permissions N/A
adding/editing/deleting of values
