### ISSUE TITLE
Tests for titles form field

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#144]
Child of #140. Depends on #147.

**Comment by kjgarza** [comment]
allowed value  47c9a1156f70e1aa51b455b1e03d8c8387d6b370
multiple values 47c9a1156f70e1aa51b455b1e03d8c8387d6b370
missing value  931276f10c5aa8e02dea04147db86c05a128900a
incorrect value(s) N/A
insufficient permissions N/A
adding/editing/deleting of values  931276f10c5aa8e02dea04147db86c05a128900a
