### ISSUE TITLE
Tests for descriptions form field

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#145]
Child of #140. Depends on #155.

**Comment by kjgarza** [comment]
power-select helpers doesn't seem to be working with bootstrap version of the select  component. https://github.com/kaliber5/ember-bootstrap-power-select/issues/19

**Comment by mfenner** [comment]
@kjgarza can you explain?

**Comment by kjgarza** [comment]
`selectChoose` is the default helper to select options in a power select. However, in the `ember-bootstrap-power-select`, ember doesn't seem to be able to find the component, your get something like, the component found is not a power-select. Similalry to the open issue in the ember-bootstrap-power-select repo. `selectChoose` does three things as far as I can see, (1) finds the select, (2) tiggers the action, (3) selects the option. With `ember-bootstrap-power-select` doesn't seem to be able to complete the first one. I'm looking at the internal tests of `ember-bootstrap-power-select` to see if we can mimic the whole find, click and select using the other test helpers.

**Comment by kjgarza** [comment]
`selectChoose` is the default helper to select options in a power select. However, in the `ember-bootstrap-power-select`, ember doesn't seem to be able to find the component, your get something like, the component found is not a power-select. Similalry to the open issue in the ember-bootstrap-power-select repo. `selectChoose` does three things as far as I can see, (1) finds the select, (2) tiggers the action, (3) selects the option. With `ember-bootstrap-power-select` doesn't seem to be able to complete the first one. I'm looking at the internal tests of `ember-bootstrap-power-select` to see if we can mimic the whole find, click and select using the other test helpers.

**Comment by mfenner** [comment]
Is this an issue about testing? As I am not aware of any issues with power-select not working properly for descriptions.

**Comment by kjgarza** [comment]
indeed its about the making the tests

**Comment by kjgarza** [comment]
allowed value 54f27c5ecb353f5136661ae8ebb625dd3e45d175
multiple values  e6d12955dd8a0d36b7ff632efed24236bb5832ef
missing value N/A
incorrect value(s) N/A
insufficient permissions N/A
adding/editing/deleting of values  e6d12955dd8a0d36b7ff632efed24236bb5832ef
