### ISSUE TITLE
Tests for creators form field

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#146]
Child of #140. Depends on #156.

**Comment by kjgarza** [comment]
allowed value e6d12955dd8a0d36b7ff632efed24236bb5832ef
multiple values  e6d12955dd8a0d36b7ff632efed24236bb5832ef
missing value 
incorrect value(s) 
insufficient permissions 
adding/editing/deleting of values  e6d12955dd8a0d36b7ff632efed24236bb5832ef
