### ISSUE TITLE
Alter placement for "Add" buttons

### ISSUE THREAD

**Issue by daslerr** [datacite/bracco#184]
User testing showed that people sometimes clicked on the "Add Creator" button (or "Add" buttons for other field sets) as a way to "submit" the Creator they were working on, rather than when they intended to make an additional Creator. This could be solved by changing where the Add buttons are placed in the layout.

**Comment by mfenner** [comment]
Fixed via https://github.com/datacite/bracco/commit/f6c862c03f182c6494bb1a1901ddc3a263002c66.
