### ISSUE TITLE
DOI Upload file is validating DOI name on update

### ISSUE THREAD

**Issue by kjgarza** [datacite/bracco#189]
DOI name shoun'dt be validated on update. Old DOI name might contain values we do not accept anymore.

It seems to be that this is happening in the DOI upload

https://usersnap.com/a/#/datacite/p/datacite-41ebcc0f/581

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_iowj)

**Comment by kjgarza** [comment]
So description is being validated with /dois/validate which will send an error if the DOI has a + sign

https://github.com/datacite/bracco/blob/9df40ec2b51da78806e5a5500327b748fde12345/app/validators/metadata.js#L14

**Comment by mfenner** [comment]
Where is the validation creating an error for a DOI with a +  sign?

**Comment by kjgarza** [comment]
the API call to /dois/validate is returning 

```
 {source: "doi", title: "Is invalid"}
```

The call is taken the DOI-name from the DOI model and although it cannot be modified it still has the + sign. So basically is failing in Lupo when one wants to validate metadata with a DOI-name with a + sing

**Comment by kjgarza** [comment]
I just noticed that there is a flag in lupo. 

``` unless: :only_validate ```

Alternatevely maybe we could skip doi-name validation on `/dois/validate`

https://github.com/datacite/lupo/blob/96a6c2c113f349128d5700c1cd0a224522dbd45c/app/models/doi.rb#L80


would that be better ??

**Comment by mfenner** [comment]
I think you are saying to not check the DOI format when you are validating a DOI that you want to update. Which makes perfect sense to me. We still need the DOI check for the validation of a new DOI.

**Comment by mfenner** [comment]
@kristian I think there are two scenarios:

* DOI exists -> validation of metadata with DOI name containing a + sign should pass
* DOI does not exist -> validation of metadata with DOI name containing a + sign should fail

In the current implementation both would fail, in your proposed implementation both would pass.

**Comment by kristian** [comment]
@mfenner, wrong @kristian... guess you meant @kjgarza

**Comment by mfenner** [comment]
Sorry, of course. Have a nice weekend.
