### ISSUE TITLE
Update Fabrica Provider Settings form with contact information

### ISSUE THREAD

**Issue by kjgarza** [datacite/bracco#195]
https://datacite.atlassian.net/wiki/spaces/TEC/pages/874577924/Collecting+and+displaying+member+information

**Comment by richardhallett** [comment]
The form has been updated based upon the mockups.
The only change I can see that I have not missed in the separation between general contact and fabrica password email.
I believe they are one in the same and think this will make things simpler.

**Comment by mfenner** [comment]
Feedback: only show provider form section titles (like **Billing Information**) when there is information.
![Bildschirmfoto 2019-05-23 um 15 38 14](https://user-images.githubusercontent.com/23151/58257221-cf587200-7d70-11e9-8662-a8733a70bfb6.png)

**Comment by mfenner** [comment]
Feedback: use appropriate labels (e.g. **Billing Contact Given Name** instead of Billing Contact Name). 

![Bildschirmfoto 2019-05-23 um 15 40 11](https://user-images.githubusercontent.com/23151/58257361-12b2e080-7d71-11e9-84ba-93fe280a8aaf.png)

**Comment by mfenner** [comment]
Feedback: fix error message. 
![Bildschirmfoto 2019-05-23 um 15 42 16](https://user-images.githubusercontent.com/23151/58257530-5efe2080-7d71-11e9-9a8f-b839a308070e.png)

**Comment by mfenner** [comment]
Feedback: Spelling (use **Twitter** instead of twitter).
![Bildschirmfoto 2019-05-23 um 15 42 16](https://user-images.githubusercontent.com/23151/58257660-9a005400-7d71-11e9-84b3-aceed7c10585.png)

**Comment by mfenner** [comment]
Feedback: properly left-align heading.
![Bildschirmfoto 2019-05-23 um 15 55 15](https://user-images.githubusercontent.com/23151/58258517-2f501800-7d73-11e9-8df8-623415b2e492.png)

**Comment by mfenner** [comment]
Feedback: is secondary billing contact optional or required?

**Comment by richardhallett** [comment]
Updates
* Twitter spelling changed
* Twitter validation error message update
* Secondary Billing contact is optional - Added text to fit.
* Updated billing contact field names to reflect other contacts.
* Added title for organization information section
* Moved titles left justfied aligned
* Only showing billing heading on overview if it has data
* Re-ordered billing contact fields

**Comment by mfenner** [comment]
Updates from me

* show ROR ID as clickable link
* use only one regex to validate Twitter account
* show Twitter account as clickable link
* don't validate additional contact information

**Comment by mfenner** [comment]
Simplified display of contact information.

![Bildschirmfoto 2019-05-23 um 23.13.08.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/3d5095f3-55ba-4309-a311-024b70d0da0e)
