### ISSUE TITLE
File Upload: Unable to update XML when full ember model is not validating

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#196]
Using the file upload, the XML is triggering full ember model validation, this means if you have things that do not necessarily match up with Embers model then it will not update the XML.
The XML is still valid metadata schema.

No errors are show in the system.

Example valid XML that can trigger this:

```
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="http://datacite.org/schema/kernel-4" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4/metadata.xsd">
  <identifier identifierType="DOI">10.70048/MVGR-RA97</identifier>
  <creators>
    <creator>
      <creatorName>Acme Inc</creatorName>
    </creator>
    <creator>
      <creatorName>Acme Inc Testing division</creatorName>
    </creator>
  </creators>
  <titles>
    <title>Testing of prototypes in the wild west with a coyoto</title>
  </titles>
  <publisher>Acme Inc</publisher>
  <publicationYear>2016</publicationYear>
  <language>en</language>
  <resourceType resourceTypeGeneral="Dataset">Dataset</resourceType>
  <version>6.12</version>
  <descriptions>
    <description descriptionType="Abstract">Desc</description>
  </descriptions>
</resource>
```

The problem here is specifically related to the creators not have a nameType, which is required to handle if giveName or familyName are used in the ember data model.
However you can not actually fix this by updating using the file upload, it will not allow you to add it in and cause an update.
The only way to fix is either directly via the API or using the Form.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_jd3v)

**Comment by richardhallett** [comment]
I've also seen this occur when no nameIdentifier is specified giving ember validation model warnings that the ORCID identifier needs to be valid for personal types.

**Comment by mfenner** [comment]
This has been fixed.
