### ISSUE TITLE
Escaped < and > cause description display to cut off rest of text

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#198]
Adding in an escaped < or > causes the description from the XML to not be displayed properly.

Example:

`Some initial text&lt;the rest of the text won't display.`

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_jhvn)

**Comment by mfenner** [comment]
This is a generic problem with HTML escaping, see for example https://stackoverflow.com/questions/36710704/text-after-symbol-gets-truncated.

This is not an easy fix. Closing this for now.
