### ISSUE TITLE
Form has infinite rendering problem with blank DOI response

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#204]
When a DOI is created with no metadata information the form does not render correctly and throws a "Error: infinite rendering invalidation detected" on refresh.

You can re-create this with using an empty DOI JSON REST API request with the payload:
{
  "data": {
    "type": "dois",
    "attributes": {
      "doi": "10.70048/basicbroken"
    }
  }
}

This will create a draft DOI but this will cause the previous problem.

My initial assumption is due to the data required for some of the form fields is not defaulted correctly causing this rendering error.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_m7nn)

**Comment by mfenner** [comment]
No longer reproducible in latest bracco release 3.3.9.
