### ISSUE TITLE
Unable to update provider accounts with ror-ids associated

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#208]
When trying to update the provider account details, the ror-id is being rejected due to missing "https://ror.org" which is now required for ROR ids.

I believe bracco is potentially stripping this and then trying to send that through to the API which rejects it.

We need to ensure you can update the provider settings ROR ID.
Additionally it would be good to be able to remove this data, at the moment attempting to remove keeps the original one in-tact.

Additionally it might be good to normalise the existing data for all providers to use the new format. Possibly a DB update.

Reproduce:

1. Goto a client that has a ror ID set (at time of writing this bug) https://doi.datacite.org/providers/datacite/settings
2. Attempt to click update, do not change any data
3. Look at network response, notice API rejecting ror id as it's missing https://

**Comment by kjgarza** [comment]
![image](https://user-images.githubusercontent.com/1092861/60892472-76309900-a25f-11e9-9f98-d41e583f5a51.png)

**Comment by mfenner** [comment]
This has been fixed.
