### ISSUE TITLE
Fabrica does not redirect to Info screen upon login

### ISSUE THREAD

**Issue by kjgarza** [datacite/bracco#218]
Confirmed and a few clients have mentioned the same issue. One needs to re-load the page to be redirected.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_uzb7)

**Comment by MaryHirsch** [comment]
@kjgarza appears to be working as expected in production. I have asked the user that reported this to check as well. ready to close
