### ISSUE TITLE
The total DOIs appearing under the "Schema Version" facet in Fabrica is not correct

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#225]
### Expected Behaviour

schema version facet displays schema versions for total of all dois

### Current Behaviour

schema version facet shows an incorrect number of dois 
https://doi.datacite.org/repositories/bl.ukda/dois and is not displaying all the schema versions

### Steps to Reproduce

1. log into fabrica production
2. view a list of dois under a repository e.g.
https://doi.datacite.org/repositories/bl.ukda/dois
3. under schema version the total is not the same as the total number of dois

### Context (Environment)

Fabrica production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_vamb)

**Comment by kjgarza** [comment]
API calls for repositories and clienst show different numbers as well

* Preparing request to https://api.datacite.org/repositories/bl.ukda/dois
* Preparing request to https://api.datacite.org/clients/bl.ukda/dois

**Comment by kjgarza** [comment]
The face is working correctly but it seems there DOIs actually have not schema_version stored in the ES index.  https://doi.datacite.org/repositories/bl.ukda/dois?client-id=bl.ukda&page=NaN&query=schema_version%3A*&sort=relevance

**Comment by kjgarza** [comment]
The large mayority of DOIs without shemaVersion data come from MDS. 

the line below get the schema version when a new doi is created.

https://github.com/datacite/lupo/blob/304c1b016dc11a7db36a8152faef538f3221d720/app/controllers/dois_controller.rb#L625

This works correctly when created from fabrica or entering json metadata, but xml metadata seems to not leave the field empty. Grabbing the version after the XML parsing (using bolognese) should work but the specs seem to need to be adjusted.
