### ISSUE TITLE
Batch transfer 258 DOIs to Potato Center

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#230]
There are 258 dois with prefix 10.21223 under the CDL.CDL client. These DOIs need to be transferred to SML.CIP.

Old client: CDL.CDL
New client: SML.CIP
DOIs: 258
Prefix: 10.21223

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_x35v)

**Comment by richardhallett** [comment]
Transferred all dois for 10.21223 to SML.CIP
