### ISSUE TITLE
The affiliation look-up does not detect correct match even when the complete organization name is entered

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#231]
### Expected Behaviour

The affiliation look up detects the correct match.

### Current Behaviour

The affiliation look-up does not detect correct match as first in the list even when the complete organization name is entered. 

### Steps to Reproduce

1. Fabrica form
2. Under affiliation type “American University” 
3. even when the complete name is entered, the correct match is still 3rd in the list

### Context (Environment)

Fabrica production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_x1oj)

**Comment by mfenner** [comment]
The sort order in the affiliation search depends on a number of factors (e.g. two separate words), typing in the full name does not guarantee that it will be the first entry in the search results. The goal is to have the affiliation name always appear in the top 10 search results.
