### ISSUE TITLE
Findable DOIs appearing with no creator or title 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#235]
### Expected Behaviour

Findable DOIs cannot be created without all of the required fields

### Current Behaviour

A user reports numerous DOIs appearing not to have a creator or title in form and summary view although this information is seen in the file upload view

### Steps to Reproduce

E.g
https://doi.datacite.org/dois/10.21405%2Flogtrend.2019.5.1.56/edit

plus the following DOIs
10.21405/logtrend.2019.5.1.12
10.21405/logtrend.2019.5.1.25
10.21405/logtrend.2019.5.1.4
10.21405/logtrend.2019.5.1.43
10.21405/logtrend.2019.5.1.20.
10.21405/logtrend.2019.5.1.50
10.21405/logtrend.2019.5.1.29
10.21405/logtrend.2019.5.1.36

### Context (Environment)

Fabrica production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_ye83)

**Comment by richardhallett** [comment]
This is a display problem only, looks like data not being loaded into the fabrica model correctly, probably because of the relation to the form.
However metadata is fine, a temporary fix can be made by just updating via file upload and the DOI's should fix themselves.

**Comment by richardhallett** [comment]
Potential related issue might be https://github.com/datacite/lupo/issues/285 - This was referring to missing publisher field.

**Comment by richardhallett** [comment]
A reassessment of this actually suggest this isn't bracco related, the search index doesn't have the correct information from the DOI.

I can reproduce by making an API call with the same XML used. With subsequent updates it does correct itself.

```{
  "data": {
    "attributes": {
      "prefix": "10.70048",
      "confirmDoi": null,
      "url": null,
      "creators": [],
      "titles": [],
      "publisher": null,
      "publicationYear": null,
      "descriptions": [],
      "xml": "PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPHJlc291cmNlIHhtbG5zPSJodHRwOi8vZGF0YWNpdGUub3JnL3NjaGVtYS9rZXJuZWwtMyIgeG1sbnM6eHNpPSJodHRwOi8vd3d3LnczLm9yZy8yMDAxL1hNTFNjaGVtYS1pbnN0YW5jZSIgeHNpOnNjaGVtYUxvY2F0aW9uPSJodHRwOi8vZGF0YWNpdGUub3JnL3NjaGVtYS9rZXJuZWwtMyBodHRwOi8vc2NoZW1hLmRhdGFjaXRlLm9yZy9tZXRhL2tlcm5lbC0zL21ldGFkYXRhLnhzZCI+CiAgPGlkZW50aWZpZXIgaWRlbnRpZmllclR5cGU9IkRPSSI+MTAuMjE0MDUvTE9HVFJFTkQuMjAxOS41LjEuNDwvaWRlbnRpZmllcj4KICA8Y3JlYXRvcnM+CiAgICA8Y3JlYXRvcj4KICAgICAgPGNyZWF0b3JOYW1lPk5hZ3ksIFZpdmllbiDDgWduZXM8L2NyZWF0b3JOYW1lPgogICAgPC9jcmVhdG9yPgogICAgPGNyZWF0b3I+CiAgICAgIDxjcmVhdG9yTmFtZT5Lb3ptYSwgVMOtbWVhPC9jcmVhdG9yTmFtZT4KICAgIDwvY3JlYXRvcj4KICAgIDxjcmVhdG9yPgogICAgICA8Y3JlYXRvck5hbWU+R3llbmdlLCBCYWzDoXpzPC9jcmVhdG9yTmFtZT4KICAgIDwvY3JlYXRvcj4KICA8L2NyZWF0b3JzPgogIDx0aXRsZXM+CiAgICA8dGl0bGU+SW5mb3Jtw6FjacOzIMOhcmFtbMOhc2kgZm9seWFtYXQgamVsZW50xZFzw6lnZSBlZ3kgbG9naXN6dGlrYWkgc3pvbGfDoWx0YXTDsyBlc2V0w6liZW48L3RpdGxlPgogIDwvdGl0bGVzPgogIDxwdWJsaXNoZXI+QkktS0EgTE9HSVNaVElLQSBLZnQuPC9wdWJsaXNoZXI+CiAgPHB1YmxpY2F0aW9uWWVhcj4yMDE5PC9wdWJsaWNhdGlvblllYXI+CiAgPHJlc291cmNlVHlwZSByZXNvdXJjZVR5cGVHZW5lcmFsPSJUZXh0Ij5hcnRpY2xlPC9yZXNvdXJjZVR5cGU+CiAgPGRlc2NyaXB0aW9ucz4KICAgIDxkZXNjcmlwdGlvbiBkZXNjcmlwdGlvblR5cGU9IlNlcmllc0luZm9ybWF0aW9uIj5Mb2dpc3p0aWthaSB0cmVuZGVrIMOpcyBsZWdqb2JiIGd5YWtvcmxhdG9rIChOeW9tdGF0b3R0IElTU046IDI0MTYtMDU1NSwgT25saW5lIElTU046IDI1NjAtMDM2MiksIDIwMTkuIGrDumxpdXMsIFYuIMOpdmZvbHlhbSwgMS4gc3rDoW08L2Rlc2NyaXB0aW9uPgogIDwvZGVzY3JpcHRpb25zPgo8L3Jlc291cmNlPg==",
      "source": "fabrica",
      "state": "draft",
      "reason": null,
      "event": null,
      "mode": "upload"
    },
    "relationships": {
      "client": {
        "data": {
          "type": "repositories",
          "id": "datacite.rph"
        }
      }
    },
    "type": "dois"
  }
}```

**Comment by richardhallett** [comment]
A further further reassessment does confirm this was due to bracco and sending empty attributes like creators: [] - These are prioritised over the value in the XML.

I've done a fix on test to prevent these being sent, this bug only occured for file upload and was "solved" because we do cancel out the titles/creators when modifying.

**Comment by richardhallett** [comment]
This has been deployed and should now be fixed.
