### ISSUE TITLE
File upload: Formats being stripped from metadata

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#236]
Format's specified in the file upload are dissapearing:

Reproduce:

1. Create a new Draft DOI containing valid XML and format xml like:
```
   <formats>
     <format>application/x-netcdf</format>
   </formats>
```
2. Move Draft DOI to findable to trigger validation of model
3. Notice XML no longer contains formats.

**Comment by mfenner** [comment]
This has been fixed by the work on the DOI form (datacite/bracco#324).
