### ISSUE TITLE
File upload: DOI validation differences draft to findable vs straight to findable.

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#237]
There appears to be a difference in what validates vs initial sending of straight to findable and using a staged approached of draft to findable.

I suspect the second workflow causes a update which triggers the validation and attempts to modify the xml submitted to match what we expect. There are specific issues around the stuff that gets changed when not expecting e.g. https://github.com/datacite/bracco/issues/236

However this bug is more that it is confusing that there is different behaviour when doing different workflows via the file upload.

An example XML that has an invalid date is a good example, going directly to Findable causes no changes, triggering an update via draft to findable, causes the date to be removed.

1. Create new Draft DOI

```
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.1/metadata.xsd">
  <identifier identifierType="DOI">10.70048/rphsimple2</identifier>
  <creators>
    <creator>
      <creatorName nameType="Personal">Hallett, Richard</creatorName>
      <givenName>Richard</givenName>
      <familyName>Hallett</familyName>
      <affiliation>DataCite</affiliation>
    </creator>
  </creators>
 <titles>
    <title xml:lang="en-US">DataCite RPH DOI Test Example</title>
  </titles>
  <publisher>DataCite</publisher>
  <publicationYear>2018</publicationYear>
  <resourceType resourceTypeGeneral="Text">XML</resourceType>
  <subjects>
    <subject>datacite</subject>
    <subject>doi</subject>
    <subject>metadata</subject>
  </subjects>
  <dates>
    <date dateType="Collected">2018-06-12 Not a valid date</date>
  </dates>
  <version>1.0</version>
  <descriptions>
    <description descriptionType="Abstract">This is a test DOI xml for RPH's purposes.</description>
  </descriptions>
</resource>
```

2. Go back in and switch to findable
3. Check XML, observe date has been removed.

Now do opposite where you go straight to Findable without draft first and notice date stays.

**Comment by mfenner** [comment]
Can no longer be reproduced.
