### ISSUE TITLE
Publisher not showing correctly in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#239]
### Expected Behaviour

The summary displays the publisher in Fabrica

### Current Behaviour

DOI not showing the publisher information in the citation in Fabrica

### Steps to Reproduce

Original issue reported for https://doi.datacite.org/dois/10.12754%2Fmsr-1999-0037

### Context (Environment)

Fabrica test and production

**Comment by mfenner** [comment]
Can't reproduce. This DOI contains SeriesInformation, and that is used in citation styles. Most citation styles omit the publisher for journal articles, which is the default, and also category here.
