### ISSUE TITLE
Transfer DOIs functionality not working in test environment

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#241]
### Expected Behaviour

Transfer DOIs from one repository to another under the same member

### Current Behaviour

In test, "transfer dois" button is greyed out

### Steps to Reproduce

1. log in as a member
2. select a doi
3. click transfer doi
4. select another repository under the same member
5. the button is greyed out. nothing happens

### Context (Environment)

Fabrica Test

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_10edf)

**Comment by richardhallett** [comment]
Fixed.
