### ISSUE TITLE
Delete OSTI.TESTPROJ

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#245]
The following client account cannot be deleted in Fabrica production. There are no prefixes or DOIs assigned to this client.

Client ID : OSTI.TESTPROJ

Please delete.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_112rn)

**Comment by MaryHirsch** [comment]
Transfer DOIs in DB from OSTI.TESTPROJ DOIs, to the DOE Generic client OSTI.DOE

**Comment by richardhallett** [comment]
This was complicated by the original "test" dois had no metadata, therefore causing them not to be updated in elasticsearch.
I had to manually use the API to set the metadata to be something, once they then got properly indexed I could transfer and then subsequently delete the client.
