### ISSUE TITLE
The Organization Name does not appear for some Consortium Organization accounts

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#251]
### Expected Behaviour

The Organization Name is saved in the record and appears when clicking "update member"

### Current Behaviour

Here is an example: https://doi.test.datacite.org/providers/esr/settings 
The Organization Name is not appearing, this consoritium organization became dissociated from the parent consortium (DOINZCO), this can be fixed by adding the consortium into the consortium org record but the update button won't work if the name is not visible

### Steps to Reproduce

1. see example https://doi.test.datacite.org/providers/esr/settings 

### Context (Environment)

Fabrica test

**Comment by mfenner** [comment]
This is related to a missing consortium for consortium organization. The issue can be addressed by not allowing a missing consortium for consortium organizations.
