### ISSUE TITLE
Create DOI functionality not working for some repositories in test

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#254]
### Expected Behaviour

Possible to create DOIs with repository accounts under a consortia 

### Current Behaviour

The UVA.LIBRA-TEST repository account cannot create DOIs

### Steps to Reproduce

1. navigate to UVA.LIBRA-TEST and "create doi"

"DOI name already exists" message appears

![Screen Shot 2019-11-14 at 11 54 13](https://user-images.githubusercontent.com/44582654/68851162-a983a880-06d5-11ea-9419-67678dcbc738.png)

### Context (Environment)

Fabrica test (consortia)

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_137b7)

**Comment by mfenner** [comment]
The error message is unrelated to the underlying problem and has been changed. The issue causing this has also been fixed.
