### ISSUE TITLE
Not possible to remove/update re3data record DOI in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#259]
### Expected Behaviour

The re3data record DOI can be removed/updated in Fabrica 

### Current Behaviour

The re3data record DOI reappears after it has been removed after hitting update DOI. 

### Steps to Reproduce

See example: https://doi.test.datacite.org/repositories/delft.jrc/settings

### Context (Environment)

Fabrica production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_14nsz)

**Comment by mfenner** [comment]
### Issues

* REST API ignores `null` value, so `re3data_id` is never reset.
* issues with updating re3data because of recent code changes (requiring `A` and `capitalize`methods)

**Comment by MaryHirsch** [comment]
Thank you but it seems that some further correction is needed.  Although in the 'Settings' page at https://doi.test.datacite.org/repositories/delft.jrc/settings the re3data URL is updated correctly, at https://doi.test.datacite.org/repositories/delft.jrc/dois the re3data record that is displayed still corresponds to that of the JRC Data Catalogue.

**Comment by mfenner** [comment]
Not an issue with the code, but external re3data API.
