### ISSUE TITLE
File Upload 2: Description/abstract displayed for older DOIs, not new ones

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#261]
### Expected Behaviour

When a new DOI is registered via the file upload, the description/abstract is displayed in the summary view e.g https://doi.datacite.org/dois/10.25620%2Fci-02_21 

### Current Behaviour

Description/abstract are missing in all newer DOIs   –  in June it worked as expected with the same procedure

### Steps to Reproduce

New without description: https://doi.datacite.org/dois/10.25620%2Fci-06_04
Older with description: https://doi.datacite.org/dois/10.25620%2Fci-02_21

### Context (Environment)

Fabrica production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_14gw3)

**Comment by MaryHirsch** [comment]
The Description shows up in DataCite XML, but not in DataCite JSON and therefore doesn’t show up in Fabrica.

**Comment by mfenner** [comment]
I can no longer reproduce this issue.
