### ISSUE TITLE
The "account is active" check box no longer appears in the repository form

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#271]
### Expected Behaviour

The "account is active" check box appears to members when they click "update repository"

### Current Behaviour

When logged in with a member account, the "account is active" checkbox does not appear (it is seen when logged in with DataCite admin)

### Steps to Reproduce

1. log in as member
2. click on update repository

### Context (Environment)

Fabrica production and test 

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1666b)

**Comment by mfenner** [comment]
This has been fixed.
