### ISSUE TITLE
"Organization name" and "organization name to display" not appearing in Member records

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#275]
### Expected Behaviour

Organization Name appears in Member record

### Current Behaviour

Organization Name disappears https://doi.datacite.org/providers/unlv/settings

### Steps to Reproduce

1. Intermittent issue  with some records e.g. https://doi.datacite.org/providers/unlv/settings

### Context (Environment)

Fabrica production

**Comment by brittadreyer** [comment]
The organization name disappears in all member records when I click "update settings" both with the Admin and the TIB login.

**Comment by mfenner** [comment]
Resolved in  bracco 3.3.9 release.
