### ISSUE TITLE
Account contact information - Multiple Emails allowed 

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#277]
Currently you can enter multiple e-mail addresses using a ";" to seperate, this will mess up things like exporting data.

We either need to disallow this explicitly and clean up the data, or accept that this is okay.

![image](https://user-images.githubusercontent.com/7294431/71352796-84f1da80-2577-11ea-80b5-64e47acfb152.png)

**Comment by mfenner** [comment]
Implemented email validation checks.

![Bildschirmfoto 2020-01-06 um 13.46.49.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/93136abc-a1bb-4f24-9d4b-7a76d61ff23c)

**Comment by mfenner** [comment]
We have two form fields for most contacts (service, technical, billing) if more than one email address is needed.
