### ISSUE TITLE
Widget type of Component  for list of DOIs

### ISSUE THREAD

**Issue by kjgarza** [datacite/bracco#279]
Based on: https://docs.google.com/document/d/1y4M8hkdkP28s-kaaxYYiJRnGMtIjkjTlbq-DqpNYKPg/

**Comment by mfenner** [comment]
@kjgarza can you explain this GitHub issue? `bracco` already has a component `doi-list`, how is this issue related?

**Comment by kjgarza** [comment]
this is for the counter display per item in the DOI list. Like in here

![image](https://user-images.githubusercontent.com/1092861/71582493-c1d74780-2b0a-11ea-8dfc-31946d935bcc.png)

**Comment by mfenner** [comment]
Is this using the Vue widget?

**Comment by kjgarza** [comment]
No. Using Emberjs

**Comment by mfenner** [comment]
@kjgarza thanks. Please add an informative description.
