### ISSUE TITLE
duplicate DOIs appearing in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#289]
### Expected Behaviour

Duplicate DOIs not possible

### Current Behaviour

2 draft DOIs with the same name appearing in Fabrica https://doi.datacite.org/repositories/cul.ciesin/dois?client-id=cul.ciesin&page=NaN&query=%2010.7927%2Fafh0-as62&sort=relevance

### Steps to Reproduce

1. a user reported that this duplicate was created after trying to delete the original draft DOI https://doi.datacite.org/repositories/cul.ciesin/dois?client-id=cul.ciesin&page=NaN&query=%2010.7927%2Fafh0-as62&sort=relevance

### Context (Environment)

Fabrica production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1960z)

**Comment by MaryHirsch** [comment]
comments from @richardhallett in support ticktet: There is no duplicate in the database, it seems instead it's a duplicate in the search index. My guess is the delete never properly deleted it from the index, but did delete it from the database. I suspect this will need further testing/investigation (i.e. a bug), but it could be related to other problems we're experiencing around performance.

**Comment by richardhallett** [comment]
For this specific user it was fixed and unable to reproduce directly. I've managed to fix the respective search indexes to reflect accurately.
