### ISSUE TITLE
Incomplete response appears for some Fabrica links

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#290]
### Expected Behaviour

When clicking on link to Fabrica you are taken directly to the page

### Current Behaviour

Incomplete response appears e.g  https://doi.datacite.org/repositories/wh.whoas/dois

### Steps to Reproduce

1. click on a link to Fabrica  https://doi.datacite.org/repositories/wh.whoas/dois

### Context (Environment)

Production

**Comment by mfenner** [comment]
This issue has been resolved.
