### ISSUE TITLE
Fields missing, update button greyed out when clicking "Update repository "

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#294]
### Expected Behaviour

Clicking "update repository" all fields are displayed

### Current Behaviour

Clicking "update repository" the repository type and certificate fields are missing, the "account active button". The update button is also greyed out and error message displayed " Account is active This account can register and update DOIs To save this repository, first resolve the errors with these fields: repository ID. "

### Steps to Reproduce

1. attempts to add service contact to this repository failed: https://doi.datacite.org/repositories/cit.sword/edit

### Context (Environment)

Production/test

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_19u2r)

**Comment by MaryHirsch** [comment]
the account is active check box is visible when logged in with admin account. Check box disappears when logged in as member/consortium organization

**Comment by mfenner** [comment]
Permission issues for consortia are tracked via datacite/lupo#433

> .
