### ISSUE TITLE
Delete repository button does not appear to be working

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#295]
### Expected Behaviour

after clicking delete repository button there is a redirect or message to indicate that the repository has been delete

### Current Behaviour

appears as though the repository is not deleted even though it appears that prefixes and dois have been migrated to a different repository. The repository to be deleted is https://doi.datacite.org/repositories/inist.irstea/settings

### Steps to Reproduce

1. navigate to this repository and try to delete it https://doi.datacite.org/repositories/inist.irstea/settings

**Comment by mfenner** [comment]
This has been resolved. The underlying problem was DOIs that were not properly indexed.
