### ISSUE TITLE
Delete 603 DOIs under GESIS.PHZH (prefix transferred to Crossref)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#299]
Prefix 10.21240 was transferred to Crossref and the DOIs were re-registered there. Please delete all 603 DOIs registered with this prefix under GESIS.PHZH

**Comment by richardhallett** [comment]
Prefix and associated DOI's deleted.

**Comment by richardhallett** [comment]
Doi's still exist in database, appears only removed from the index.

**Comment by richardhallett** [comment]
Pretty certain they are gone properly this time, also deleted the repository.
