### ISSUE TITLE
FTP links not accepted in url field in file upload and form in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#300]
### Expected Behaviour

ftp links accepted in url field in form and file upload
### Current Behaviour

entering an ftp link in url field generates error

### Steps to Reproduce

1. enter ftp://ftp.library.noaa.gov/noaa_documents.lib/2013%20NOAA%205%20Year%20Plan_FINAL%20version.pdf in url field

### Context (Environment)

Fabrica test and production

**Comment by MaryHirsch** [comment]
deploy to production

**Comment by richardhallett** [comment]
Bracco was deployed to production but this appears to still be an issue occurring in production.

**Comment by richardhallett** [comment]
Working now, deployment problem prevented fix.
