### ISSUE TITLE
DOIs not appearing in Fabrica after the were created

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#301]
### Expected Behaviour

DOIs indexed after creation

### Current Behaviour

A number of DOIs reported to not be appearing in Fabrica after they were created via both form and file upload:

examples:

https://doi.datacite.org/dois/10.34739%2Fzn.2019.49.08

10.34739/zn.2019.49.09
10.34739/zn.2019.49.10
10.25967/490085
10.25967/490158
10.25967/490165

### Steps to Reproduce

1. https://doi.datacite.org/dois/10.34739%2Fzn.2019.49.08 this doi exists but does not appear under the repository PSNC.UPH

### Context (Environment)

Fabrica production

**Comment by MaryHirsch** [comment]
another one 10.5885/45591aw-f9b906cc647948e0

**Comment by richardhallett** [comment]
Reindexed DOI's.
