### ISSUE TITLE
Add state support to billing address

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#303]
For organisations, add abiity to lookup a state based upon ISO or predefined list.
Specifically needs to be able to standardise and then match across to Salesforce.

**Comment by richardhallett** [comment]
This is more complicated in that if we want to do the lookup in fabrica we have to bring in quite a large dataset, the best complete library I can find for state lookup is via: https://www.npmjs.com/package/iso3166-2-db - But under their own guidance they suggest not bringing everything in on the frontend.

I'm not sure this is worth the overhead to frontend just to have lookup of billing states. Additionally I'm not sure this solves the problem of anybody who wants to update their data via the API.

**Comment by mfenner** [comment]
This has been addressed in #343.
