### ISSUE TITLE
Not possible to update repository when logged in with a repository account

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#305]
### Expected Behaviour

When logged in with repository account clicking "update repository" leads to update form view

### Current Behaviour

When logged in with the repository account, when clicking on "update repository" the user is redirected to the info tab on the dashboard

### Steps to Reproduce

1. login in with repo account, not reproducible with admin
2. e.g. https://doi.test.datacite.org/repositories/datacite.mary 

### Context (Environment)

Fabrica test 

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1axdv)

**Comment by mfenner** [comment]
This is a permission (abilities) problem for user with role `client_admin`. Will fix and add test coverage.
