### ISSUE TITLE
Password reset fields set to type text

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#311]
The input fields for the password reset are set to input type="text" this has the behaviour of letting the browser try to remember this as plain text as opposed to only just for passwords.

This is potentially bad security as it could end up exposing the users passwords in other prompts unintentionally.

Suggestion is to set input type to "password", alternatively we could expand this to be a toggled switch to show the password visibility and set the text field to have "autocomplete=off" to attempt to avoid any accidental browser remembering.

**Comment by mfenner** [comment]
+1 for type="password".

**Comment by richardhallett** [comment]
Made the change to type="password", Deployed to test, will go to production in next release.
