### ISSUE TITLE
Markdown is not support in the description field for repositories and dois

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#364]
### Expected Behaviour

Mark down is support in description field in Fabrica for both repositories and dois

### Current Behaviour

Mark down doesn't format

### Steps to Reproduce

1.  https://doi.test.datacite.org/repositories/example.bla

### Context (Environment)

Fabrica

**Comment by mfenner** [comment]
Added markdown support for repository description, similar to what we already support for members.

Markdown support for the description DOI field was never planned, and should be discussed in a separate issue if needed.
