### ISSUE TITLE
Date not appearing in citation if only publisherYear included in metadata

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#384]
### Expected Behaviour

Date is shown in the citation 

### Current Behaviour

Date is not shown in the citation if the metadata is missing the dates metadata in it and only contains the publisherYear.

### Steps to Reproduce

1. example https://doi.datacite.org/dois/10.34747%2Fg6yb-3412

### Context (Environment)

Fabrica 

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_1hgn7)

**Comment by davclark** [comment]
Thanks @MaryHirsch for triaging this issue. To expand on the behavior, the publicationYear IS returned from the following datacite JSON query:

`curl -LH 'accept: application/vnd.datacite.datacite+json' https://doi.org/10.34747/g6yb-3412`

But NOT if we use Citeproc JSON (which I think queries https://data.crosscite.org):

`curl -LH 'accept: application/vnd.citationstyles.csl+json' https://doi.org/10.34747/g6yb-3412`

So there appears to be an issue with the way the metadata is registered for citeproc.

If the datacite API works for all DOIs, we can just use that (but still it would be good if Years entered in Fabrica were functional across the different APIs and tools). I also sent this question to @MaryHirsch via email - but I figure it's worth having here if others have this issue.
