### ISSUE TITLE
Internal testing DOI form new fields

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#398]

**Comment by mfenner** [comment]
Issue: **Description** group under required fields and not recommended fields.

![Bildschirmfoto 2020-04-14 um 15 54 16](https://user-images.githubusercontent.com/23151/79232792-422a7a00-7e68-11ea-8231-9e75e526bba2.png)

**Comment by mfenner** [comment]
Issue: Make the **Required Fields** more prominent.

![Bildschirmfoto 2020-04-14 um 15 56 08](https://user-images.githubusercontent.com/23151/79233029-97ff2200-7e68-11ea-817b-2692e3fa4689.png)

**Comment by mfenner** [comment]
Issue: need to explain SPDX to users, e.g. in the help text and with a link.

<img width="1053" alt="Bildschirmfoto 2020-04-14 um 18 51 55" src="https://user-images.githubusercontent.com/23151/79251897-15369100-7e81-11ea-8cb0-8d3b3bc5014f.png">

**Comment by mfenner** [comment]
Issue: use **
<img width="1160" alt="Bildschirmfoto 2020-04-14 um 18 53 30" src="https://user-images.githubusercontent.com/23151/79252131-6d6d9300-7e81-11ea-8d60-4c00439cbd78.png">
funder** or **funder name** instead of **funding reference** in search box.

**Comment by mfenner** [comment]
Issue: consider how to best display the award URI (or whether to not give the example).
<img width="965" alt="Bildschirmfoto 2020-04-14 um 18 57 15" src="https://user-images.githubusercontent.com/23151/79252424-df45dc80-7e81-11ea-9255-10dff2b0b309.png">

**Comment by mfenner** [comment]
Issue: Crossref Funder ID should use standard DOI format (https://doi.org instead of http://dx.doi.org).

<img width="1163" alt="Bildschirmfoto 2020-04-14 um 19 04 23" src="https://user-images.githubusercontent.com/23151/79253057-e4eff200-7e82-11ea-8229-a70e1f4330a4.png">

**Comment by mfenner** [comment]
Issue: add whitespace between asterix and label.

<img width="1203" alt="Bildschirmfoto 2020-04-14 um 19 22 46" src="https://user-images.githubusercontent.com/23151/79254792-8d06ba80-7e85-11ea-8a16-004fbc223f95.png">

**Comment by mfenner** [comment]
Issue: DOI included in alternate Identifier field.

<img width="1212" alt="Bildschirmfoto 2020-04-15 um 21 42 06" src="https://user-images.githubusercontent.com/23151/79381628-8d28b800-7f62-11ea-9089-52fc20ee13d5.png">

**Comment by mfenner** [comment]
Issue: missing optional resourceTypeGeneral

<img width="1153" alt="Bildschirmfoto 2020-04-16 um 04 43 35" src="https://user-images.githubusercontent.com/23151/79408936-deee3400-7f9c-11ea-835f-0016d282687b.png">

**Comment by kjgarza** [comment]
That is in the code but its codnitioned. Whne I read the schema i understood that it was only nedded when the related identifier was hasMetadata. I guess one can just move it out of the if-clause https://github.com/datacite/bracco/blob/0faedef4c27cdde29dabf44a14af957f413ea35e/app/templates/components/doi-related-identifier.hbs#L113

**Comment by mfenner** [comment]
resourceTypeGeneral for relatedIdentifiers was introduced to better support Scholix.

**Comment by mfenner** [comment]
![Bildschirmfoto 2020-04-18 um 05.17.55.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/3af1e33c-86d2-44eb-bbc2-23295316b668)

**Comment by mfenner** [comment]
Issue: contributorType does not show in form

![Bildschirmfoto 2020-04-18 um 09.41.12.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/1f90cb25-d33c-4872-8ff6-f81604176906)

**Comment by mfenner** [comment]
Issue: use label in plural form for all properties that can be plural.

**Comment by mfenner** [comment]
Issue: allow deletion of the first option field. Align delete button with input field.![Bildschirmfoto 2020-04-18 um 19.24.00.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/ba1e45ad-7826-42d6-a506-4a7bdbb76daf)

**Comment by mfenner** [comment]
Issue: navigation becomes too complicated with lots of metadata.

**Comment by mfenner** [comment]
Issue: warning messages instead of error messages for draft DOIs increase the complexity for properly highlighting errors in the form.

**Comment by mfenner** [comment]
Issue: show controlled list of relation types in human readable form (also applies to resourceTypeGeneral).

![Bildschirmfoto 2020-04-20 um 09.54.39.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/7d490b88-e4be-48c1-9aac-7e28cf10e6ee)

**Comment by mfenner** [comment]
Issue: ROR name and id not showing up in form.

![Bildschirmfoto 2020-04-20 um 17.54.23.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/39d61f29-eca8-4eda-b5de-ff085d8c6701)

**Comment by mfenner** [comment]
Issue: support info URI for rights

![Bildschirmfoto 2020-04-20 um 23.42.53.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/6a9d2079-277f-4546-bae9-5cccbd5c57e8)

**Comment by mfenner** [comment]
Validation of info URIs addressed via https://github.com/datacite/bracco/pull/406.

**Comment by mfenner** [comment]
Fixing alternative identifiers addressed via https://github.com/datacite/bracco/pull/407.
