### ISSUE TITLE
Set password functionality is not working for consortium accounts

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#401]
### Expected Behaviour

The "set password" functionality allows the account creator to set a password for the account.

### Current Behaviour

The "set password" function doesn't work. Nothing happens when "set password" button is clicked

### Steps to Reproduce

1. example https://doi.test.datacite.org/providers/moia 

<img width="1396" alt="Screen Shot 2020-04-22 at 11 57 24" src="https://user-images.githubusercontent.com/44582654/79968699-c98f7300-8490-11ea-84ac-54a64c783817.png">

### Context (Environment)

Fabrica test

**Comment by mfenner** [comment]
This cound not be reproduced.
