### ISSUE TITLE
Providers not showing up in facet

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#409]
### Expected Behaviour

Facet shows number of repositories by provider in repository list view

### Current Behaviour

The facet is empty. The name of this facet should also be changed from "providers"

### Steps to Reproduce

1. https://doi.datacite.org/repositories view provider facet on the left

### Context (Environment)

Fabrica production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nq51)

![Bildschirmfoto 2020-05-08 um 12.31.19.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/a3339f3f-757c-49cb-bb93-4b239491f1db)

**Comment by mfenner** [comment]
There is a similar issue with consortium organizations for provider prefixes:

![Bildschirmfoto 2020-05-08 um 12.29.54.png](https://images.zenhubusercontent.com/5698de08638e718c99601957/7da43b6d-d0be-4675-b3f6-68bfc0018f86)
