### ISSUE TITLE
Refresh view when assigning or removing prefix

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#422]
Currently the view is not updated in Fabrica.

![image](https://user-images.githubusercontent.com/1092861/92938506-eaab2d00-f44c-11ea-9062-1ba615cba39c.png)

**Comment by kjgarza** [comment]
using the ember-inspector one can see the storage getting updated and on redirection one can see the **model** and **afterModel** hooks being triggered. however, the query that retrieves data doesn't bring the updated data. the quey is in the **model** hook.

**Comment by kjgarza** [comment]
need to modify https://github.com/datacite/bracco/blob/dc89788/app/routes/repositories/show/prefixes/index.js

**Comment by kjgarza** [comment]
` this.store.query('repository-prefix', params, { reload: true })` seems to be looking at the index, unfortunately the indexing task for the prefix is very slow
