### ISSUE TITLE
Related identifier metadata remains blank even after deletion in fabrica form

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#429]
### Expected Behaviour

Related identifier can be removed from Fabrica form

### Current Behaviour

Even when deleted, the Related Identifier remains in the metadata

### Steps to Reproduce

1. example: https://doi.test.datacite.org/dois/10.70126%2Fs2y0-sc75

### Context (Environment)

Fabrica 

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nt79)

**Comment by kjgarza** [comment]
@maryhirsch  I cannot reproduce this. 

the only way I can reproduce it is if one **clears** the identifier input box. But that is not deleting.  One needs to **click the trash can to delete**. And that always works.

Comments?
