### ISSUE TITLE
newly created repositories not appearing in Fabrica test

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#431]
### Expected Behaviour

Newly created repositories can be searched and retrieved in Fabrica

### Current Behaviour

Search not finding new repositories and they do not appear under the member/consortium org e.g. DELFT.SURF

### Steps to Reproduce

1. example https://doi.test.datacite.org/repositories/DELFT.SURF 

### Context (Environment)

Fabrica test

**Comment by richardhallett** [comment]
Is this reproducable in Production? @MaryHirsch

**Comment by MaryHirsch** [comment]
could not reproduce in production

**Comment by mfenner** [comment]
Fixed via https://github.com/datacite/lupo/pull/570
