### ISSUE TITLE
Salesforce DKIM key. add the CNAME and Alternate CNAME records in the DNS for your domain.

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#434]
Salesforce has published the TXT records for this DKIM key to DNS. Before activating this key, add the CNAME and Alternate CNAME records in the DNS for your domain.

https://datacite.lightning.force.com/lightning/setup/EmailDKIMList/page?address=%2F09P1U000000fxj5

**Comment by sarala** [comment]
@MaryHirsch I can't access the link above - insufficient privileges. Can you please give me access to the page?

**Comment by mjbuys** [comment]
@sarala I have edited your access so should be able to access the link now.

**Comment by sarala** [comment]
@MaryHirsch, this is done from our end.

**Comment by MaryHirsch** [comment]
Thanks. We should allow at least 12 to 24 hours for the changes to be recognised by Salesforce
