### ISSUE TITLE
Name field not autopopulated when unknown radio button selected

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#438]
### Expected Behaviour

The form autopopulates the name field when the given name and family name are entered

### Current Behaviour

The "name" field does not autopopulate, seems to be when the radio button "unknown" is selected (this is default)

<img width="1038" alt="Screen Shot 2020-06-18 at 14 52 49" src="https://user-images.githubusercontent.com/44582654/85022736-fea80100-b173-11ea-83cc-b1379b964d90.png">

### Steps to Reproduce

1. create a doi via form

### Context (Environment)

Fabrica form

**Comment by mfenner** [comment]
@MaryHirsch this is expected behaviour. Automatic name generation based on given name and family name requires nameType `Personal`.

**Comment by MaryHirsch** [comment]
@mfenner this was reported by an end user. it could be confusing. Maybe this could be a feature request for a message to select the "person" radio button

**Comment by kjgarza** [comment]
@mfenner @MaryHirsch Could we clarify what the correct behaviour is this feature? This doesn't seem to be a bug.

**Comment by mfenner** [comment]
Defaulting to nameType personal has created issues in the past, and thus we have moved away from it. I suggest to update the documentation, but not make any changes in code.
