### ISSUE TITLE
ARDC DOIs with no metadata in findable state

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#442]
### Expected Behaviour

all DOIs have the required metadata fields and can be updated

### Current Behaviour

+900 old ARDC DOIs with no metadata in Findable state

### Steps to Reproduce

1. [usyd_missing_dois.txt](https://github.com/datacite/bracco/files/4837108/usyd_missing_dois.txt)

### Context (Environment)

Production

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o2c5)

**Comment by richardhallett** [comment]
I attempted to reimport these based on the database, but after investigation I can find no metadata for these DOIs.
They are quite old though, dating from 2012, it is possible they were registered without any metadata in the first place.

I would suggest ARDC registers metadata of some description for these.

**Comment by mfenner** [comment]
We have a fairly significant number of DOIs from the early days of DataCite that don't have all the required metadata for various reasons. I suggest to change their state to `registered` so that they continue to resolve but don't show up in the public Elasticsearch index. As `registered` DOIs also need all required metadata, this needs to be done "manually".

**Comment by mfenner** [comment]
ARDC or other members can of course update the metadata of these DOIs, and they see them in the API and Fabrica when in `registered` state.

**Comment by richardhallett** [comment]
I've moved all 902 dois in ANDS.CENTRE11 to registered manually.
https://doi.datacite.org/repositories/ands.centre11/dois

Based on the conversation in front ticket, that is what they wanted as well.
