### ISSUE TITLE
Fabrica doesn't throw a UI error when Wrong namespace and xsi:schemaLocation in included metadata upload. (Only API error appears)

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#445]
### Expected Behaviour

Metadata that turns green in file upload  is validates

### Current Behaviour

Metadata turns green but DOI cannot be created

### Steps to Reproduce

1. copy metadata below into file upload
2. set to "findable"
3. click "create"
4. nothing happens, 422 generated

<img width="1231" alt="Screen Shot 2020-07-15 at 09 38 37" src="https://user-images.githubusercontent.com/44582654/87517569-4f315200-c67f-11ea-8593-5c0bd68fe4a2.png">

### Context (Environment)

Fabrica 

### Possible Implementation

```
<?xml version="1.0" encoding="UTF-8"?>
<resource xmlns="https://schema.datacite.org/meta/kernel-4.3/" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="https://schema.datacite.org/meta/kernel-4.3/ https://schema.datacite.org/meta/kernel-4.3/metadata.xsd">
<identifier identifierType="DOI">mus.preis.1820-70</identifier>
<titles>
	<title>Musikalische Preisausschreiben 1820-1870</title>
	<title titleType="Subtitle">Grundriss, Datenbank und Bibliografie auf Grundlage von Musikperiodika</title>
</titles>
<creators>
	<creator>
		<creatorName nameType="Personal">Frank Hentschel</creatorName>
		<givenName>Frank</givenName>
		<familyName>Hentschel</familyName>
		<affiliation>University of Cologne</affiliation>
	</creator>
	<creator>
		<creatorName nameType="Personal">Andreas Domann</creatorName>
		<givenName>Andreas</givenName>
		<familyName>Domann</familyName>
		<affiliation>University of Cologne</affiliation>
	</creator>
	<creator>
		<creatorName nameType="Personal">Carola Bebermeier</creatorName>
		<givenName>Carola</givenName>
		<familyName>Bebermeier</familyName>
		<affiliation>University of Cologne</affiliation>
	</creator>
	<creator>
		<creatorName nameType="Personal">Clemens Kreutzfeldt</creatorName>
		<givenName>Clemens</givenName>
		<familyName> Kreutzfeldt</familyName>
		<affiliation>University of Cologne</affiliation>
	</creator>
	<creator>
		<creatorName nameType="Personal">Aleksander Mar</creatorName>
		<givenName>Aleksander</givenName>
		<familyName>Mar</familyName>
		<affiliation>University of Cologne</affiliation>
	</creator>
	<creator>
		<creatorName nameType="Personal">Jonas Traudes</creatorName>
		<givenName>Jonas</givenName>
		<familyName> Traudes</familyName>
		<affiliation>University of Cologne</affiliation>
	</creator>
</creators>
<publisher>University of Cologne</publisher>
<publicationYear>2020</publicationYear>
<resourceType resourceTypeGeneral="Dataset">Dataset with Text</resourceType>
<subjects>
	<subject subjectScheme="DDC">780 Musicology</subject>
	<subject subjectScheme="DDC">900 History</subject>
	<subject subjectScheme="wikidata" valueURI="https://www.wikidata.org/wiki/Q164204">musicology (Q164204)</subject>
	<subject subjectScheme="wikidata" valueURI="https://www.wikidata.org/wiki/Q50675"> historiography (Q50675) </subject>
</subjects>
<contributors>
	<contributor contributorType="DataCollector">
		<contributorName>Rebeka A. Dainy</contributorName>
		<givenName>Rebeka A. </givenName>
		<familyName>Dainy</familyName>
	</contributor>
	<contributor contributorType="DataCollector">
		<contributorName>Julia Eberhardt</contributorName>
		<familyName>Eberhardt</familyName>
		<nameIdentifier>Julia</nameIdentifier>
	</contributor>
	<contributor contributorType="DataCollector">
		<contributorName>Maik Käster</contributorName>
		<givenName>Maik </givenName>
		<familyName>Käster</familyName>
	</contributor>
	<contributor contributorType="DataCollector">
		<contributorName>David Matäna</contributorName>
		<givenName>David</givenName>
		<familyName>Matäna</familyName>
	</contributor>
	<contributor contributorType="DataCollector">
		<contributorName>Maarten Sterckx</contributorName>
		<givenName>Maarten</givenName>
		<familyName>Sterckx</familyName>
	</contributor>
</contributors>
<dates>
	<date dateType="Collected">January 2017 to December 2019</date>
</dates>
<language>de</language>
<fundingReferences>
	<fundingReference>
		<funderName>Deutsche Forschungsgemeinschaft (DFG)</funderName>
	</fundingReference>
</fundingReferences>
</resource>

```

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nwyd)

**Comment by kjgarza** [comment]
its probably related only with the metadata file. the functionality works with defautlt metadata from the schema page, look at https://doi.stage.datacite.org/dois/10.70041%2Fywzf-gv20, http://schema.datacite.org/meta/kernel-4.3/

**Comment by MaryHirsch** [comment]
yes, I agree. But the file upload turns green, which makes it extremely difficult to find the problem

**Comment by kjgarza** [comment]
@MaryHirsch , that's fine. I am just trying to clarify the BUG. 

Because then is not about `Valid metadata is not creating a DOI` but it's more like `Invalid metadata throw does not throw an error in the user interface when rejected by the API`

**Comment by kjgarza** [comment]
Resource header is wrong of the metadata file is wrong. It should be

> <resource xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://datacite.org/schema/kernel-4" xsi:schemaLocation="http://datacite.org/schema/kernel-4 http://schema.datacite.org/meta/kernel-4.3/metadata.xsd"><identifier identifierType="DOI">10.2233/mus.preis.1820-70</identifier>

Basically it has the wrong addresses.

The validator doesn't fail because this is not part of the metadata, this header is use for the validation.


xmlns defines default namespace, which states, that all nodes within project node and without an namespace-alias will be in http://datacite.org/schema/kernel-4 namespace by default.

xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" defines namespace - http://www.w3.org/2001/XMLSchema-instance, and gives it a new alias - xsi

xsi:schemaLocation is an attribute schemaLocation of "http://www.w3.org/2001/XMLSchema-instance" namespace. It contains pairs of values - namespace URI and schema location link for xsd-schema file of that namespace. It can contain many pairs of values - one xsd file for every defined namespace URI. That means link http://schema.datacite.org/meta/kernel-4.3/metadata.xsd contains xsd schema with definition of http://datacite.org/schema/kernel-4  namespace.
