### ISSUE TITLE
Delete DK.GBIF in test

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#446]
Some DOIs still assigned to DK.GBIF in test in the db https://doi.test.datacite.org/repositories/dk.gbif/dois. They should be transferred to DK.TEST so that the DK.GBIF account can be deleted.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nxcl)

**Comment by mfenner** [comment]
All 23 DOIs in DK.GBIF have been indexed and transferred to DK.TEST. DK.GBIF can be deleted.

**Comment by mfenner** [comment]
I needed to manually update all 23 DOIs to draft state, as they didn't have valid metadata, which caused issues with the transfer.
