### ISSUE TITLE
 The resourceTypeGeneral cannot be added to a DOI with schema 3 in the Form

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#447]
### Expected Behaviour

DOI updates validate even with older version of the schema

### Current Behaviour

The resourceTypeGeneral cannot be added via the form

### Steps to Reproduce

1. https://doi.datacite.org/dois/10.25673%2F32731/edit

### Context (Environment)

Fabrica 

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nx05)

**Comment by kjgarza** [comment]
Schema 3 metadata can be updated to schema 4 form via **the API** or the **upload form**.
