### ISSUE TITLE
Citation for a DOI is showing "internal server error"

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#449]
### Expected Behaviour

Fabrica displays the citation of the DOI

### Current Behaviour

The DOI citation shows "internal server error"

### Steps to Reproduce

https://doi.datacite.org/dois/10.5885%2F45654ce-270458b4b50f45aa
<img width="1311" alt="Screen Shot 2020-07-20 at 16 38 31" src="https://user-images.githubusercontent.com/44582654/87950632-daf41580-caa7-11ea-8fb5-2cef3c277f46.png">

### Context (Environment)

Fabrica 

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nxat)

**Comment by mfenner** [comment]
This issue has been resolved, and was a secondary effect of the DOI not being indexed in Elasticsearch.
