### ISSUE TITLE
Registered DOIs not retrieved in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#450]
### Expected Behaviour

DOIs can be searched and retrieved in Fabrica 

### Current Behaviour

Registered DOIs not retrieved in Fabrica

### Steps to Reproduce

examples:

PSNC
10.24423/engtrans.960.20200720 e.g https://doi.datacite.org/dois/10.24423%2Fengtrans.960.20200720
10.24423/engtrans.1182.20200720

ARDC

10.25919/5BC1DD6C3879E e.g https://doi.datacite.org/dois/10.25919%2F5bc1dd6c3879e
10.25919/5BC1DF51E814D
10.25919/5CB6F1C7BA909
10.25919/5CC957420154F
10.25919/5D4D37F59BF98
10.25919/5D4D3887D7DDD
10.25919/5D9548E2CA1F3
10.4225/08/57ABF87058F16
10.4225/08/57AC2A8EA7D8E
10.4225/08/5801C67A1126A
10.4225/08/5A6FE16846A67

SUBGOE.RUB
10.23692/iMex.18.2 e.g https://doi.datacite.org/dois/10.23692%2FiMex.18.2
10.23692/iMex.18.4 
10.23692/iMex.18.6 
10.23692/iMex.18.8

### Context (Environment)

Fabrica

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2nxg5)

**Comment by mfenner** [comment]
There was a problem with the DOI index that wasn't properly indexing. Switching the index solved the problem, but the index is missing DOIs. I created a new inactive DOI index, which is now reindexing all DOIs in the background. This should be completed in 24 hrs, and I will then switch indexes.
