### ISSUE TITLE
Subject Scheme URI dissapears after updating

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#453]
### Expected Behaviour

Subject Scheme URI can be added to the DOI record

### Current Behaviour

Subject Scheme URI disappears after saving 

### Steps to Reproduce

1. Go to a DOI e.g https://doi.datacite.org/dois/10.35010%2Fecuad:13503/edit
2. add Subject Scheme URI e.g.http://id.loc.gov/authorities/subjects
3. update
4. click out of the DOI
5. click back in
6 the Subject Scheme URI is gone

### Context (Environment)

Fabrica

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o07p)

**Comment by richardhallett** [comment]
Fixed, the problem was in using SchemeURI not SchemeUri which was expected from json serialised version.
