### ISSUE TITLE
Validation with different schema versions fail when forcing to schema 4

### ISSUE THREAD

**Issue by kjgarza** [datacite/bracco#454]
use schema docs from the schema website

**Comment by richardhallett** [comment]
Is this a bug? What is the problem here, because there would obviously be validation errors if just changing schema version.

**Comment by kjgarza** [comment]
updates correctly

schema 3.0, https://schema.datacite.org/meta/kernel-3.0/example/datacite-example-complicated-v3.0.xml, https://doi.stage.datacite.org/dois/10.4124%2F40n9-vv35

schema 3.0 without resource type general, https://doi.stage.datacite.org/dois/10.70131%2Ftest_doi_5d8c3b774037f, drop form error and needs to add resourceType General

schema 3.1 https://schema.datacite.org/meta/kernel-3.1/example/datacite-example-full-v3.1.xml,  https://doi.stage.datacite.org/dois/10.4124%2Fv09t-qw62

schema4.0, https://schema.datacite.org/meta/kernel-4.0/example/datacite-example-full-v4.0.xml,https://doi.stage.datacite.org/dois/10.4124%2F658z-sf90

schema 4.1 , https://schema.datacite.org/meta/kernel-4.1/example/datacite-example-full-v4.1.xml, https://doi.stage.datacite.org/dois/10.4124%2Fan2m-7m87

**Comment by kjgarza** [comment]
schema 2.3, https://doi.stage.datacite.org/dois/10.70126%2F2303-bw79, drops erros for lack of resource type and needs o add resource

**Comment by mfenner** [comment]
Thanks @kjgarza this is great. Can you test an example with Schema 3 and contributor type "Funder"? We have 230K with this metadata and there is a breaking change in schema 4.

**Comment by mfenner** [comment]
Another breaking change is removing resourceTypeGeneral "Film" in schema 3. Only 1539 DOIs, but can you check what happens when you feed them into the form. I assume the form will ask for a new resourceTypeGeneral.

**Comment by kjgarza** [comment]
updates on these type will only fail from the API response. there is no validation of non-controlled type in the [form as far as i can see](https://github.com/datacite/bracco/blob/6b064ad/app/validators/contributor-type.js#L37).  Now unfortunately the API is not giving us good errors at the moment, all errors reported seem related to CORS, which is werid but that is the current case: 

![image](https://user-images.githubusercontent.com/1092861/92454682-0dc1ac80-f1c1-11ea-853e-515aa9685015.png)

Could it be the API is always returning CORS ERROR for all errors? (in stage)

**Comment by kjgarza** [comment]
weirdly enough the API is actually logging the error in **Datadog**, but that errors is not being reported to **Fabrica** 

```
App 15696 output: {"contributor', attribute 'contributorType":["[facet 'enumeration'] The value 'Funder' is not an element of the set {'ContactPerson', 'DataCollector', 'DataCurator', 'DataManager', 'Distributor', 'Editor', 'HostingInstitution', 'Other', 'Producer', 'ProjectLeader', 'ProjectManager', 'ProjectMember', 'RegistrationAgency', 'RegistrationAuthority', 'RelatedPerson', 'ResearchGroup', 'RightsHolder', 'Researcher', 'Sponsor', 'Supervisor', 'WorkPackageLeader'}. at line 24, column 0"],"@timestamp":"2020-09-08T08:38:08.260+00:00","@version":"1","severity":[],"host":[]}
```

**Comment by mfenner** [comment]
@kjgarza what is the action in Fabrica that is causing the CORS error. Updating metadata via form? Can you give the URL and details?

**Comment by kjgarza** [comment]
```
Access to XMLHttpRequest at 'https://api.stage.datacite.org/dois/10.4124%2Fp7c8-j832' from origin 'https://doi.stage.datacite.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.

lib.js:7 PATCH https://api.stage.datacite.org/dois/10.4124%2Fp7c8-j832 net::ERR_FAILED
```

![image](https://user-images.githubusercontent.com/1092861/92462478-d3f5a380-f1ca-11ea-97a7-0871a3698456.png)

**Comment by mfenner** [comment]
Can you provide more details, in particular the HTTP verb? Updating DOI metadata works for me in Fabrica Stage.

**Comment by kjgarza** [comment]
its PATCH

```
PATCH https://api.stage.datacite.org/dois/10.4124%2Fp7c8-j832 net::ERR_FAILED
```

have you tried to update this DOI https://api.stage.datacite.org/dois/10.4124%2Fp7c8-j832 ???

I think it fails with all the DOIs that have something wrong in the metadata

**Comment by mfenner** [comment]
Thanks. PATCH is supported, and what was used in my metadata updates from Fabrica. I can look into how CORS handles error messages.

In the meantime, can you add validation of contributor types to Fabrica? In this issue or a new one. Fabrica is not so good in handling API errors graciously.

**Comment by mfenner** [comment]
I could update DOI 10.4124/p7c8-j832 in Fabrica Stage. The update fails when changing the DOI state to "findable". It seems that `lupo` is not sending proper CORS headers when an error occurs, and I will investigate.

We still need to update Fabrica to check for contributor types. As fixing the CORS issue still generates an API error that Fabrica can't handle properly.
