### ISSUE TITLE
 consortium lead account doesn't seem to able transfer DOIs

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#460]
### Expected Behaviour

Consortium lead account has permission to transfer a DOI from one repository to another

### Current Behaviour

The transfer DOI button is not working as expected

### Steps to Reproduce

1. In test, when the repository ID is pasted into the transfer field, the repository is not found and the transfer button is inactive
2. ARDC reported that they were not able to transfer to DOI in production

### Context (Environment)

Test 

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o3h1)

**Comment by kjgarza** [comment]
I cannot reproduce this 

went to https://doi.test.datacite.org/dois/10.12685%2F21dd-6d13/transfer

Selected :"figshare.dud" but DID NOT click transfer

Went to

https://doi.test.datacite.org/repositories/figshare.dud/dois?client-id=figshare.dud&page=NaN&query=10.12685%2F21dd-6d13&sort=relevance

and 

https://doi.test.datacite.org/dois/10.12685%2F21dd-6d13

still shows in the right repository

and did not find the DOI.

**Comment by MaryHirsch** [comment]
Then I think the bug is that consortoim organizations cannot transfer DOIs between repositories under the same consortium organization

**Comment by kjgarza** [comment]
@MaryHirsch but they front ticket says you cannot reproduce that either, so basically we cannot reproduce any of it. I am missing something here?

**Comment by MaryHirsch** [comment]
![Screen Shot 2020-09-18 at 16 03 31](https://user-images.githubusercontent.com/44582654/93606582-8fd38180-f9c8-11ea-9f2a-f78b53ba8e55.png)

Now i can reproduce. Consortium acccount cannot transfer dois between repositories under the same consortium organizations

**Comment by kjgarza** [comment]
@MaryHirsch I think you have to write the name of the repository not the ID

**Comment by MaryHirsch** [comment]
![Screen Shot 2020-09-18 at 16 40 22](https://user-images.githubusercontent.com/44582654/93610694-ad571a00-f9cd-11ea-84bc-96b3ce8a88c7.png)

That does not work either and it should be possible to transfer using the ID

**Comment by mfenner** [comment]
@kjgarza can you address this using Fabrica tests? That is safer than working with the UI manually.

**Comment by kjgarza** [comment]
@MaryHirsch  I actually think the reason why this is not enabled for consortium leads is the same reason that consortium leads (CLs) do not appear in the stats portal. In the data model, CL are not connected to repositories or the DOIs under their COs. So they do not see any repository to transfer to. E.g., https://api.datacite.org/providers/ESTDOICO

**Comment by mfenner** [comment]
@kjgarza this is not exactly true, you can query dois and repositories by `consortium_id`. I think the question is what functionality we want to support.

**Comment by mfenner** [comment]
I have enabled functionality for consortium lead accounts to transfer DOIs and repositories. This only required a few minor tweaks in Fabrica and API.
