### ISSUE TITLE
Alternative identifiers not appearing in Fabrica form and API

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#461]
### Expected Behaviour

Alternative identifiers appear in form and API

### Current Behaviour

Alternative Identifiers only appear in file upload view

### Steps to Reproduce

1. correct: https://api.datacite.org/dois/10.24397/PANGLOSS-0000007  
2. incorrect: https://api.datacite.org/dois/10.24397/PANGLOSS-0000008  

### Context (Environment)

Production

**Comment by kjgarza** [comment]
closing in favour of https://github.com/datacite/lupo/issues/641
