### ISSUE TITLE
Issue with related identifier field in form

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#464]
### Expected Behaviour

Related identifier field validates when correct information is entered

### Current Behaviour

When updating DOIs through the "update DOI (form)"  we get this error message  ("To save this DOI, first resolve the errors with these properties: relatedIdentifier" ). This prevents us from validating any modification via this interface, yet we haven’t changed the way of writing this property. (ex 10.24397/ pangloss-0006038). However the updating can be done using "update DOI (file upload) or via the API

### Steps to Reproduce

1. https://doi.datacite.org/dois/10.24397%2Fpangloss-0006036/edit

### Context (Environment)

Fabrica 

### Possible Implementation

.

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o42d)

**Comment by kjgarza** [comment]
@MaryHirsch have you been able to reproduce this?
