### ISSUE TITLE
Logging into Fabrica with consortium organization account directs user to repositories tab

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#467]
### Expected Behaviour

Log in user lands on settings tab

### Current Behaviour

User lands on "repositories" tab

### Steps to Reproduce

1. log in with ID "DataCite"
<img width="1413" alt="Screen Shot 2020-09-29 at 08 29 22" src="https://user-images.githubusercontent.com/44582654/94521182-e8f3ae80-022d-11eb-9f81-0573c75ba69c.png">

![Screen Shot 2020-09-28 at 12 44 16](https://user-images.githubusercontent.com/44582654/94423095-606f0280-0188-11eb-87a2-2b13104d6af5.png)

### Context (Environment)

Fabrica 

### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2o4gl)

**Comment by MaryHirsch** [comment]
Consortium Lead, Consortium Orgs and Repositories should land on Settings tab when logging in to Fabrica.

**Comment by kjgarza** [comment]
this will be fixed in ur next release cycle
