### ISSUE TITLE
Wrong logo appears in member account in test Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#476]
### Expected Behaviour

The logo of the member organization appears in their account in Fabrica

### Current Behaviour

Kudos logo appearing in HBZ account in test

### Steps to Reproduce

1. https://doi.test.datacite.org/providers/fhcj

<img width="1379" alt="Screen Shot 2020-11-02 at 12 37 59" src="https://user-images.githubusercontent.com/44582654/97865416-75e8c680-1d0a-11eb-86d7-876765c04419.png">

### Context (Environment)

Fabrica test

### Possible Implementation

LikeBe the first to like this

**Comment by richardhallett** [comment]
I'm not sure this is a bug, it just has the wrong logo updated, I dont know why this is the case, but it is the test system, it does not use the same logo data as production.

There is an issue with a delay of being updated which is a seperate issue: https://github.com/datacite/bracco/issues/470

I'm closing this unless there is a specific bug of not being able to change it (although that might be #470)
