### ISSUE TITLE
Authors not appearing in alphabetical order in citation

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#486]
#### Expected Behaviour

Authors appear in alphabetical order in citation

#### Current Behaviour

Authors not appearing in alphabetical order in citation

#### Steps to Reproduce

Correctly: https://doi.datacite.org/dois/10.34943%2Fff20b227-509f-4ed0-8096-28be5a0de8f0

Incorrectly: https://doi.datacite.org/dois/10.34943%2Fc9271419-eeb2-4580-8d0d-01e870c7ab5f​

### Context (Environment)

Fabrica Production

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oaqd)

**Comment by ChantelRidsdale** [comment]
@MaryHirsch and @mfenner I just wanted to touch base on this. I've never submitted a Github issue, so unsure what the process/ expected timeline for this type of thing is

**Comment by mfenner** [comment]
@ChantelRidsdale don't worry about details or formalities.

Can you explain why you expect the authors to appear in alphabetical order? Citation styles don't really change the author order in the metadata, and that is determined by whoever generates the metadata. In some disciplines alphabetical order is common (e.g. high-energy physics), but that is not the case for many other disciplines.

**Comment by ChantelRidsdale** [comment]
@mfenner, thank you for your response. Absolutely, I'll explain. Our organization has several Indigenous Community partners, and there is an effort for Self-Determination for data and research output ownership. ONC has implemented alphabetical citations in an effort to discourage our name being listed first, and instead listing organizations platonically in alphabetical order, not prioritizing any one over the other. The citation in our back end does show as alphabetical, the order is just changed between sending the record to DataCite. this is why we are so confused. 
If you have any other questions, please do not hesitate, 
Chantel
