### ISSUE TITLE
DOI appears in draft state in list view and findable in the DOI record

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#487]
#### Expected Behaviour

DOI: 10.18730/wsxx6 appears in the same state in all views in Fabrica

#### Current Behaviour

10.18730/wsxx6 appears in both darft and findable state

#### Steps to Reproduce

1. https://doi.datacite.org/dois?page=NaN&query=10.18730%2Fwsxx6&sort=relevance
2. https://doi.datacite.org/dois/10.18730%2Fwsxx6

### Context (Environment)

Fabrica production.

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oas5)

**Comment by richardhallett** [comment]
This no longer appears to be the case.
It is possible the fix on a seperate issue related to duplicated DOIs was causing some differences in state to appear, when the index was then cleaned it has now fixed.

Closing unless reproducable with different example.
