### ISSUE TITLE
Submit password button does not react after resetting a password or receiving a password set email

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#489]
#### Expected Behaviour

The submit password button allows password to be set

#### Current Behaviour

Submit password button does not react after resetting a password or receiving a password set email

#### Steps to Reproduce

1. reset password datacite.datacite
2. follow link
3. set password
4. nothing happens

reproducible in different browsers

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ob11)

**Comment by mfenner** [comment]
Fixed via datacite/lupo#687.
