### ISSUE TITLE
Update Fabrica to align with new contacts model in REST API

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#491]
The goal is to avoid any significant changes in functionality while supporting the new contacts REST API endpoint.

**Comment by mfenner** [comment]
One visual change is a new `Contacts` tab for each member, and as a top-level tab.
![Bildschirmfoto 2021-02-08 um 19 55 16](https://user-images.githubusercontent.com/23151/107267870-be212e80-6a47-11eb-8ab4-30abee751fea.png)

Contacts can be filtered by role and clicking on any contact allows editing of the contact information

![Bildschirmfoto 2021-02-08 um 19 57 24](https://user-images.githubusercontent.com/23151/107268028-e9a41900-6a47-11eb-9fa3-219f5187e076.png)

**Comment by mfenner** [comment]
Roles are assigned in the member settings, using the same seven roles as before.

![Bildschirmfoto 2021-02-08 um 19 59 11](https://user-images.githubusercontent.com/23151/107268223-253ee300-6a48-11eb-92a8-90a560f9414f.png)

The settings for `voting`, `service` and `billing` can't be deleted, as these are required fields.

**Comment by mfenner** [comment]
When saving the provider settings, the roles of all contacts of the provider are updated, based on the roles assigned in the provider form.

**Comment by mfenner** [comment]
The REST API provides an optional `?include=contacts` to load all contacts of a provider. There is no separate data model for roles, only contacts and providers.

To implement the assigning of roles, I set up two components (`provider-contacts` and `provider-contacts-edit`) to handle assigning roles, and for example making sure that roles are only used once.

**Comment by mfenner** [comment]
Roles are optional and the number of contacts not limited. Email addresses must be unique (in the context of a provider).

Contacts can be deleted, but that in fact updates the contact with an `deleted-at` timestamp, similar to what we do with providers and repositories.

**Comment by richardhallett** [comment]
I wonder if this should show their email address as well, because otherwise it's hard to understand the duplicates.
![image](https://user-images.githubusercontent.com/7294431/107369003-82d33e00-6ae1-11eb-894e-aad03501fe37.png)
