### ISSUE TITLE
Upgrade sentry

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#493]

**Comment by svogt0511** [comment]
Sentry was upgraded with [Fabrica SW Update Issues](https://app.zenhub.com/workspaces/datacite-5930fcc4ba512f05402b55b1/issues/gh/datacite/bracco/711).  It can't be updated to 7.0.0 until Fabrica is updated to use ember-auto-import 2.0.0  It will be upgraded appropriately with future Fabrica updates.
