### ISSUE TITLE
Generate new repository ID button missing

### ISSUE THREAD

**Issue by lizkrznarich** [datacite/bracco#508]
## Expected Behaviour
The Repository ID field in Fabrica on /repositories/new includes a circle icon button that allows generating a new random ID

## Current Behaviour
The circle icon button is not displayed

## Steps to Reproduce
1. Log into Fabrica as member
2. Visit /repositories and click Add Repository
3. Circle icon missing from Repository ID field on /repositories/new

### Screenshots
<img width="1277" alt="Screen Shot 2021-01-29 at 12 52 21 PM" src="https://user-images.githubusercontent.com/8026886/106316114-d87e2f80-6231-11eb-900a-0a0127cdc29a.png">

### Further details
Button missing in both test and production

### Hypothesis
Code includes ```<i class="fas fa-refresh"></i>```
Font Awesome 5 set does not contain icon named refresh - the same icon is now called sync-alt https://fontawesome.com/icons?d=gallery&q=refresh

### Possible Implementation
Replace ```fa-refresh``` with ```fa-sync-alt``` . Also replace in  [doi-doi.hbs](https://github.com/datacite/bracco/blob/f65a9c9c35e73000164c9427d90ec9a4cf16fd2b/app/templates/components/doi-doi.hbs#L230)

**Comment by richardhallett** [comment]
@bklaing2 Please go ahead and merge your PR and close this

**Comment by svogt0511** [comment]
@bklaing2 - closing this issue. This fix is included in today's Fabrica 4.3.0 release

**Comment by svogt0511** [comment]
Closing.
