### ISSUE TITLE
relatedIdentifier field appears in JSON but not XML metadata of a DOI

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#518]
#### Expected Behaviour

The relatedIdentifiers information is visible in JSON and XML metadata formats

#### Current Behaviour

For this DOI https://doi.datacite.org/dois/10.7302%2Fz23r0r29 the JSON shows relatedIdentifier information but not the xml. the relatedIdentifiers field is populated in the form.

#### Steps to Reproduce

https://doi.datacite.org/dois/10.7302%2Fz23r0r29

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2of4l)

**Comment by mutanthumb** [comment]
Hi-
If it help at all I used this method to update the "relatedIdentifier" metadata:

curl -v -X PUT -H "Content-Type: application/vnd.api+json" --user umich.library:[redacted passwd] -d @doi_update.json https://api.datacite.org/dois/10.7302/Z23R0R29 

Contents of doi_update.json:

`{
  "data": {
    "attributes": {
      "relatedIdentifiers": [
        {
          "relationType": "IsCitedBy",
          "relatedIdentifier": "https://doi.org/10.1117/12.2293584",
          "relatedIdentifierType": "DOI"
        }
      ]
    }
  }
}`

**Comment by richardhallett** [comment]
Apologies on the delay on this, I've attempted to re-create the problem however and I can not see any problems with relatedIdentifiers not appearing, all the example DOIs appear to be fine.

If this is still occurring we can re-open but given the time frame this is possible this got fixed in a related issue.
