### ISSUE TITLE
The DOIs tab is not rendering correctly for inist.cea

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#525]
#### Expected Behaviour

The full list of 10 DOIs is displayed

#### Current Behaviour

Only the top 3 DOIs are shown https://doi.datacite.org/repositories/inist.cea/dois  

#### Steps to Reproduce

1. Go to https://doi.datacite.org/repositories/inist.cea/dois 
2. Problem looks to be related to https://doi.datacite.org/dois/10.25720%2Fveda-c13h

### Context (Environment)

Fabrica production

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2og5x)

**Comment by DimitriPapadopoulos** [comment]
Indeed, https://doi.datacite.org/dois/10.25720%2Fveda-c13h itself sometimes looks weird:
![veda-c13h](https://user-images.githubusercontent.com/3234522/112498086-7c91dc00-8d86-11eb-9784-9f3b5a32a33f.png)

**Comment by DimitriPapadopoulos** [comment]
While I don't see any obvious error in the XML data of this DOI, please note that at some point I had directly modified the XML using _Update DOI (File Upload)_.

**Comment by svogt0511** [comment]
In production.  Closing the issue.
