### ISSUE TITLE
Can't add new contact with same email as previously deleted contact

### ISSUE THREAD

**Issue by lizkrznarich** [datacite/bracco#529]
## Current behavior
1. Remove roles from contact on /provider/ID/edit
2. Delete contact on /contacts/ID/edit
3. Attempt to add new contact with the same email as deleted contact on /contacts/new
4. Clicking Add contact has no effect; "Please enter a valid email address" displayed
5. HTTP response ```{"errors":[{"source":"email","title":"Should be unique per provider"}]}```

## Expected behavior
It should be possible to add a new contact using a previously deleted email address.

<img width="1258" alt="Screen Shot 2021-03-29 at 3 14 09 PM" src="https://user-images.githubusercontent.com/8026886/112895004-2f717b00-90a2-11eb-80b9-5e86509cc488.png">

**Comment by mfenner** [comment]
This is the intended behaviour. We keep deleted contact information to export this information to Salesforce. What needs fixing is showing a meaningful error message. This message has been implemented, but is not showing for some reason.

**Comment by mfenner** [comment]
The error message has been fixed.
