### ISSUE TITLE
Not possible to create new accounts in test, the add member button does nothing after filling in the required fields

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#538]
#### Expected Behaviour

Add new organizational accounts to fabrica test

#### Current Behaviour

The add member button does nothing after filling in the required fields

#### Steps to Reproduce

1. https://doi.test.datacite.org/providers/new

### Context (Environment)

Fabrica test

**Comment by richardhallett** [comment]
This appears to only affect Chrome, the specific behaviour seems to be fill in 
Member ID (auto generated)
Member Name
Member Display Name
System Email

Then click Add Member, nothing happens except for the button is greyed out to prevent clicking. No obvious Javascript console errors and no network request was made to create the account.

In firefox an error is thrown but the account is actually created, I believe this to be a seperate problem.

**Comment by svogt0511** [comment]
Closing this in favor of Issue #544.
