### ISSUE TITLE
Problems with setting passwords for new accounts when the contact information is not provided

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#542]
#### Expected Behaviour

Password set works regardless of whether the contact information is provided

#### Current Behaviour

When a new account is created the password set function does not work if the contact info is not included in the record.

#### Steps to Reproduce

1. Set up a new fabrica account
2. Click on automated set password email
3. nothing happens
4. add contact and contact role
5. trigger pw reset
6. set password works

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ogwl)

**Comment by svogt0511** [comment]
@MaryHirsch, @brittadreyer - I just deployed a [pull request](https://github.com/datacite/bracco/pull/554) that should fix this issue.  I am going to close this issue.  I have tested this fix, but if you find it is not working as expected we can re-open this ticket.

**Comment by svogt0511** [comment]
The issue still exists.  We need to remove checking for contacts from the form.  The prior fix only took care of one case.  

Here is t[he thread from slack #support](https://datacite.slack.com/archives/C0CFZNZFE/p1629835218002900).

**Comment by richardhallett** [comment]
See pull request but I had a quick look and thought why not just do the disable by sending a flag on password change. See PR, if you agree this'll probably fix it.
