### ISSUE TITLE
Contacts disappear from the contact roles in the member settings after updating

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#549]
#### Expected Behaviour

Contacts are saved in the member settings after update

#### Current Behaviour

Contacts disappear from the contact roles in the member settings after updating

#### Steps to Reproduce

1.  In consortium org settings, assign Service Contact and click Update Organization
2. Contact appears to have saved
3. navigate to another tab (e.g. Contacts) and go back to the Settings page, the contact has disappeared
https://doi.test.datacite.org/providers/lydm

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ohxx)

**Comment by MaryHirsch** [comment]
note: after clicking back and forth a few times the contact roles did appear updated

**Comment by svogt0511** [comment]
I tried this in stage.  I am wondering if it is related to Issue #541.

**Comment by errortryagain** [comment]
I am consortium lead and am facing the same issue. A page refresh seems to settle the issue for the moment, but once I return to the member settings at a later point in time or after a logout, it reoccurs.

Before page refresh:
![grafik](https://user-images.githubusercontent.com/87866100/126798413-1f681179-a520-4661-ba3b-50694241432b.png)

After page refresh:
![grafik](https://user-images.githubusercontent.com/87866100/126798815-5ff7505f-220c-44bd-8e41-43032b220481.png)

**Comment by jezcope** [comment]
To add another data point to this, I've noticed the following is consistently reproducible:

1. Log in as Consortium Lead
2. Search Consortium Organisations for an org that is known to have up-to-date contact details
    - No contacts are shown in the search result, and the "Please provide this information." message appears instead
3. Click through from the search result to the org's detail page
    - The correct contact details are shown on this page
4. Use the Back button to return to the search results
    - Now the Service contact is shown in the search results as expected
5. Refresh the search results with the browser Reload button
    - The "Please provide this information." warning reappears

**Comment by KellyStathis** [comment]
@jezcope, we've experienced this behaviour too with our Consortium Lead account. I think it is documented here also: https://github.com/datacite/bracco/issues/541

**Comment by brittadreyer** [comment]
The new member WASCAL entered five contacts to their member account (IIEU). But when they wanted to assign roles to the contacts in the member settings they are not visible.
![image.png](https://images.zenhubusercontent.com/5ffc5e38fd1ff8516f2caded/2dd5725f-8430-49bc-8f4d-2103df18d23a)

**Comment by svogt0511** [comment]
@Britta, I just checked, the contacts for IIEU appear to be there (in the contacts table), but not in the provider.  I am going to take some time today to see if I can finally figure this out.

**Comment by svogt0511** [comment]
@brittadreyer There is a work-around.  The data is there.  This is a display problem.  If they open the 'Update Member' form and it says there are no contacts, press the redisplay button and that should go away.  
![image](https://user-images.githubusercontent.com/4681304/180457266-8ecdb8c0-fd55-4dd5-9f39-0eb82198275c.png)

I know this is an awful workaround and I am still looking at it to see if we can just fix the problem.  But in the meantime, they should be able to set their contacts.

**Comment by svogt0511** [comment]
Fixed in [Fabrica SW Update Issues.](https://app.zenhub.com/workspaces/datacite-5930fcc4ba512f05402b55b1/issues/gh/datacite/bracco/711)
