### ISSUE TITLE
Form does not send alternateIdentifiers

### ISSUE THREAD

**Issue by richardhallett** [datacite/bracco#551]
Form is sending empty data when trying to set alternateIdentifiers.

Reproduce
1. Create findable DOI with form
2. Add alternate Idefntifiers
3. Notice resulting metadata is missing alternateidentifiers

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2ojpx)

**Comment by errortryagain** [comment]
We are noticing the same issue also for DOIs created via the form in the draft state.

**Comment by richardhallett** [comment]
This is now fixed and in test/production.
