### ISSUE TITLE
The Facet total on the consortium dashboard does not match the number of repositories in the list in the Repositories tab

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#553]
#### Expected Behaviour

Facet total equals total number of repositories shown in the list view in Fabrica

#### Current Behaviour

The Facet total does not match the number of repositories in the list

#### Steps to Reproduce

Example; INISTCO
![Screen Shot 2021-06-10 at 11 27 16](https://user-images.githubusercontent.com/44582654/121502100-22490480-c9e0-11eb-828c-c86f209f4d7f.png)

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://frontapp.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2oic5)

**Comment by kjgarza** [comment]
i think the facet only lists 10 items (years in this case), that's normal behavior.   Could it be that the missing repos are from 2011 or older

**Comment by codycooperross** [comment]
I confirmed the hypothesis above based on ES results.
