### ISSUE TITLE
Upgrade browsers list used by Ember

### ISSUE THREAD

**Issue by digitaldogsbody** [datacite/bracco#575]
Bracco throws a lot of warnings about outdated browser data when running the test suites and recommends running `yarn upgrade`.

I think that the potential for a few packages to get confused / break by a sweeping upgrade is reasonably high, so it is probably better to try just upgrading the `browserlist` package and seeing how that goes.

**Comment by svogt0511** [comment]
Will be included in datacite/datacite#1510.

**Comment by svogt0511** [comment]
This has been done and deployed with [PR#628](https://github.com/datacite/bracco/pull/628).
