### ISSUE TITLE
Update bracco dependencies

### ISSUE THREAD

**Issue by digitaldogsbody** [datacite/bracco#594]
Once the "test on PR workflow" is fixed in https://github.com/datacite/bracco/issues/593, we can test and merge the various pending Dependabot PRs as appropriate.

Separately, there are some legacy packages in the bracco dependencies list (see https://github.com/datacite/bracco/commit/3243e5fe24cd43f1dc15431b818d671e4a4db42e for an example of one that was recently removed), and it would be good to a) audit these and remove any unused ones, and b) update the versions of core packages where possible

**Comment by svogt0511** [comment]
Will be included in datacite/datacite#1510.

**Comment by digitaldogsbody** [comment]
I have already made quite a lot of progress on this - but didn't quite have time to finish it during the last tech debt week

**Comment by digitaldogsbody** [comment]
It might be different in terms of compatibility with the later Ember versions. I wonder if the best approach might be to do the main Ember upgrade first, and then re-create my process? Otherwise I can try to find the time to fix up the last remaining issue (see the PR discussion https://github.com/datacite/bracco/pull/600) and we can merge that first.

**Comment by digitaldogsbody** [comment]
There is also the extra factors that some of these upgrades are:
a) to sub-dependencies further down the tree, so not updated by the `yarn update` procedure
b) mandated by security issues rather than compatibility issues (i.e identified solely via `yarn audit`)

**Comment by svogt0511** [comment]
Most of these been done and deployed with [PR#628](https://github.com/datacite/bracco/pull/628).  The one in this list that hasn't been upgraded is acorn.  The audit I did in that pull request is not perfect and I think some things have come up since that was done.  I am opening a new github issue to upgrade acorn and any additional new dependabot security issue.
