### ISSUE TITLE
Add GOST R 7.0.5-2008 to the list of citation styles

### ISSUE THREAD

**Issue by zcc39r** [datacite/bracco#60]
It would be useful for Russian clients.

**Comment by mfenner** [comment]
@zcc39r Is this style included in citationstyles.org? We use the styles listed at https://github.com/citation-style-language/styles

**Comment by zcc39r** [comment]
Sure, that style is in this list. See https://github.com/datacite/bracco/pull/61 .

**Comment by mfenner** [comment]
Sorry, but we are not accepting additional citation styles in DOI Fabrica at this point. There are more than 5000 styles, so we need to be very careful what we support. You can always use https://citation.crosscite.org.
