### ISSUE TITLE
If the affiliationIdentifier metadata is entered in XML does not display in the Form

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#620]
#### Expected Behaviour

When affiliationIdentifier metadata is included in the xml file, this is displayed if a user updates via the Form

#### Current Behaviour

affliationIdentifier metadata saved in XML is not displayed in the Form in Fabrica. It is saved in the API

#### Steps to Reproduce

See example DOI created with an xml file containing affiliationIdentifier metadata https://doi.test.datacite.org/dois/10.17596%2Fbx7z-na33

```
  <creators>
    <creator>
      <creatorName nameType="Organizational">DataCite</creatorName>
      <affiliation affiliationIdentifier="https://ror.org/04wxnsj81" affiliationIdentifierScheme="ROR" schemeURI="https://ror.org">DataCite</affiliation>
    </creator>
  </creators>
```

affiliationIdentifier metadata is saved in JSON: https://api.test.datacite.org/dois/10.17596/bx7z-na33 

In the Form the affiliation metadata is not displayed: https://doi.test.datacite.org/dois/10.17596%2Fbx7z-na33/edit

### Context (Environment)

Fabrica 

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2vqqd)

**Comment by svogt0511** [comment]
@MaryHirsch - This issue is the same as #550.  I will close this when PR #657 is deployed.
