### ISSUE TITLE
Service contact cannot be saved in a Repository account

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#625]
#### Expected Behaviour

The service contact information can be added and saved in Repository accounts in Fabrica

#### Current Behaviour

When the service contact is entered into the respective fields in the Repository account, the information is not saved

#### Steps to Reproduce

1. Go to a repository account e.g. https://doi.test.datacite.org/repositories/datacite.mary/edit
2. Add the "service contact"
3. Update the record
4. Reopen it a note the service contact has not been saved

### Context (Environment)

Fabrica 

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2wamt)

**Comment by kjgarza** [comment]
it is a documented feature. 

this is somewhat pre `dev journey`. So i guess you will need to investigate what happened here: https://github.com/datacite/bracco/commit/03c3b405e683a800d7e858b34f2f29d7927bd7ff
