### ISSUE TITLE
Fabrica Software Upgrade

### ISSUE THREAD

**Issue by svogt0511** [datacite/bracco#629]
Formerly: Vulnerabilities and unaddressed dependabot security updates.

See the: [Fabrica Software Upgrade Epic](https://app.zenhub.com/workspaces/datacite-5930fcc4ba512f05402b55b1/issues/datacite/datacite/1603)

The goal this week is to get to a point where we can do regular updates following a process and to look into what is involved in the octane upgrade.  To start, we need to do npm module updates, move ember data to 3.15 and take care of as many security updates as possible.

Most of these been done and deployed with [PR#628](https://github.com/datacite/bracco/pull/628).  The one in that list that hasn't been upgraded is acorn.  The audit I did in that pull request is not perfect and I think some things have come up since that was done.  I am opening this new github issue to note that acorn still needs a security upgrade and that there are additional new dependabot security issues which should be addressed, perhaps at the next bug week or technical debt week.

I would like to add to this parent package updates where possible and deleting unused packages per Mike's comment, below.  Additionally, any reasonably easy update should be done at this time.

Related to issue #585

**Comment by digitaldogsbody** [comment]
Acorn appears in the tree in multiple locations - most of them can be upgraded without issue (see https://github.com/datacite/bracco/pull/600/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R201-R202).

It was the packages using 5.7.3 that were an issue, and we might want to think about upgrading the parent packages as a way to resolve this.

**Comment by svogt0511** [comment]
That is part of the plan.  I am in total agreement that Fabrica definitely needs to upgrade a number of packages and delete unused ones.
