### ISSUE TITLE
Move prefix assignment out of Bracco to Lupo on repository creation.

### ISSUE THREAD

**Issue by svogt0511** [datacite/bracco#639]
Repositories can be created where prefixes are not assigned.  It does not happen often, but it happened yesterday.  There was a short [discussion in slack #support](https://datacite.slack.com/archives/C0CFZNZFE/p1660556863768209) about this.  The [papyrus.cbwggn repository](https://doi.datacite.org/repositories/papyrus.cbwggn) was created but no prefix was assigned.  After some investigation I found that the API call to create the repository was returning a 422 error, regardless of the fact that the repository had been created successfully.  That can be seen in these [log messages](https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logsV2:logs-insights$3FqueryDetail$3D$257E$2528end$257E$25272022-08-12T17*3a24*3a59.000Z$257Estart$257E$25272022-08-12T17*3a23*3a00.000Z$257EtimeType$257E$2527ABSOLUTE$257Etz$257E$2527Local$257EeditorString$257E$2527fields*20*40timestamp*2c*20*40message*0a*7c*20filter*0a*40message*20like*20*2fPOST*2f*20and*0a*28*40message*20like*20*2frepositories*2f*20or*0a*20*40message*20like*20*2fprefixes*2f*29*0a*7c*20sort*20*40timestamp*20desc*0a*7c*20limit*201000$257EisLiveTail$257Efalse$257EqueryId$257E$2527d23bf590-5458-4cb9-bf74-95d9c56106c5$257Esource$257E$2528$257E$2527*2fecs*2fclient-api$257E$2527*2fecs*2fmember-api$2529$2529). 
 Because the API all returned an error on repository creation, Fabrica did not create the prefix.  

The fix for this would be to move the prefix creation from Bracco to Lupo, in the API call which is used to create a repository.  That would assure that prefix assignment happens if repository creation is successful making them part of the same operation, even if some kind of error is signalled after repository creation.  Putting repository assignment it in Bracco after the API call returns gives too much opportunity for this error to happen.

The current workaround is for staff_admin to assign a prefix when this happens.

RELATED:

These 2 pull requests must be scheduled to be deployed simultaneously:

- PR#datacite/lupo#855
- PR#datacite/bracco#649

See https://github.com/datacite/bracco/pull/649 for 'TESTING and DEPLOYMENT'.

LEFT TO DO:

- [X] Update prefix-bug branch from the latest lupo master branch  and re-test.
- [x] Update prefix-bug branch from the latest bracco master branch  and re-test.
- [ ] Schedule for release of both lupo and bracco.
- [ ] Possible ADR to document how prefixes are assigned.  It is a side effect when a repository is created and has an effect when testing prefixes with respect to repositories and providers. This has caused some tests to break and needs to be considered when writing tests.  For ex, this test failed for that reason:

`bundle exec rspec ./spec/graphql/types/member_type_spec.rb:211`

**Comment by MaryHirsch** [comment]
Another example from a Consortium Lead 
Repository ID: ZMQU.NKIWMZ
