### ISSUE TITLE
When a DOI created in XML with the file upload including language attributes for subject headings when updated in the Form, the language attributes disappear from the XML 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#647]
#### Expected Behaviour

 Language attributes included in the XML via file upload are retained even when the DOI is updated via the Form in Fabrica

#### Current Behaviour

When a DOI created in XML with the file upload including language attributes for subject headings, when updated in the Form, the langauge attibutes disappear from the XML 

#### Steps to Reproduce

1. Create a DOI in XML including language attributes for subject headings in draft status
2. updated the same DOI via the Fabrica form in order to change its status from draft to findable, 
3. the language attributes were gone after saving 

Can be reproduced with this DOI: https://doi.test.datacite.org/dois/10.17596%2Fvfm8-4x79 

  <subjects>
    <subject xml:lang="en-US" schemeURI="http://dewey.info/" subjectScheme="dewey" classificationCode="000">computer science</subject>
  </subjects>

after updating via the form the xml:lang attibute also disappears from the json https://api.test.datacite.org/dois/10.17596%2Fvfm8-4x79

[6856e52d4fce957a4ee7602469895a0bdedd28e8.pdf](https://github.com/datacite/datacite/files/9583214/6856e52d4fce957a4ee7602469895a0bdedd28e8.pdf)

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_2yuz9)

**Comment by codycooperross** [comment]
I think this can be easily resolved by adding a `lang` attribute to the subject model.

I checked a few other properties that also allow an `xml:lang` attribute in the DataCite Metadata Schema v4.4 XSD. The omission of the latter three in bracco (and elsewhere) may be deliberate, though the first two appear to be bugs.

- subject: not included in bracco model
- rights: not included in bracco model (along with a few other attributes that have been commented out)

- creator.creatorName: not included in bracco model, not picked up by datacite_reader in bolognese, not indexed in lupo
- contributor.contributorName: not included in bracco model, not picked up by datacite_reader in bolognese, not indexed in lupo
- publisher: not included in bracco doi model, not not picked up by datacite_reader in bolognese, not indexed in lupo

**Comment by kaysiz** [comment]
@MaryHirsch @codycooperross should we also add language for subject and rights in the form?

**Comment by MaryHirsch** [comment]
I think this is more a question for dev/product team

**Comment by kaysiz** [comment]
@MaryHirsch @codycooperross I do not see `lang` defined in the schema https://support.datacite.org/docs/datacite-metadata-schema-v44-recommended-and-optional-properties#6-subject for `subject` model. Should we still proceed with this.

**Comment by MaryHirsch** [comment]
@kaysiz See note on page 12 of the schema doc: NOTE:
XML provides an xml:lang attribute10 that can be used on the properties Title, Subject, Rights,
Description, and RelatedItem Title, as well as on the properties Creator,
Contributor and Publisher for organizational names

**Comment by kaysiz** [comment]
@MaryHirsch Thank you.

**Comment by codycooperross** [comment]
@kaysiz You can also check the XSD for the current Schema version (in this case, 4.4) to see what properties specifically permit `xml:lang` attributes. For example, for `subject`: https://github.com/datacite/schema/blob/44b58fb485341483274a67594db9d51f625bb288/source/meta/kernel-4.4/metadata.xsd#L151  

I think because this bug doesn't involve the form presentation or behavior, we can leave the form as-is. We might be able to find an old product spec to determine why the `xml:lang` attribute was excluded in the form, but the absence appears deliberate.
