### ISSUE TITLE
Fabrica Test - Title link in metadata on DOI detail page uses the wrong handle server

### ISSUE THREAD

**Issue by svogt0511** [datacite/bracco#670]
When saving the link, bracco seems to save it correctly, however, in generating the link, bracco uses the staging environment handle server (handle.stage.datacite.org) instead of the test environment handle server (handle.test.datacite.org).  This is why it seems that the 'Update DOI' form doesn't update the DOI url correctly.  It does. However, the link generated for the DOI detail page is wrong.  Notice in the screen grab, below, that the link (screen grab lower left) for the title resolves to handle.stage.datacite.org instead of handle.test.datacite.org. 

![image](https://user-images.githubusercontent.com/4681304/199587821-5f004b63-3284-45e8-84cb-475103bc9864.png)

The bit of code in the next screen grab is responsible for the problem:

![image](https://user-images.githubusercontent.com/4681304/199588406-6195894b-88d6-4d8d-82d1-507925181b83.png)

**Comment by codycooperross** [comment]
The issue was resolved by this PR: https://github.com/datacite/bracco/pull/843
