### ISSUE TITLE
DOI relatedIdentifiers in URL format may not validate in Fabrica form

### ISSUE THREAD

**Issue by codycooperross** [datacite/bracco#709]
### Describe the bug

Entering a DOI relatedIdentifier in a URL format may not validate in the Fabrica form, causing issues with creating and saving valid relatedIdentifier metadata. 

#### Steps to Reproduce

Enter relatedIdentifier `https://doi.org/10.1080/00393630.2018.1504449` for a registered or findable DOI in the Fabrica form. 

#### Hypothesis

The DOI URL format may need to be added to the identifier-format validator: 

https://github.com/datacite/bracco/blob/main/app/validators/identifier-format.js

**Comment by KellyStathis** [comment]
In this example it does detect it correctly as a DOI, but I think there is an issue with the prefix length in one of the regular expressions. `https://doi.org/10.1080/00393630.2018.1504449` does not work, but for example `https://doi.org/10.108000/00393630.2018.1504449` is okay. Same issue encountered with `https://doi.org/10.5281/zenodo.7629200`
