### ISSUE TITLE
Inconsistent builds and failing CI due to cache issues

### ISSUE THREAD

**Issue by digitaldogsbody** [datacite/bracco#713]
When we have upgrades to dependencies, occasionally workflows will fail to run with unpredictable errors despite local builds working fine

e.g:
```
  - errorType: Build Error
  - location:
    - column: [undefined]
    - file: [undefined]
    - line: [undefined]
    - treeDir: [undefined]
  - message: [BroccoliMergeTrees] error while merging the following:
  1.  [Funnel: Packaged Ember CLI Internal Files]
  2.  [BroccoliMergeTrees: Full Application]
  3.  [BroccoliMergeTrees: TreeMerger (custom transform: fastbootShim)]
  4.  [BroccoliMergeTrees: Packaged Tests]
Merge error: conflicting capitalizations:
vendor/moment/locale/en-SG.js in /tmp/broccoli-1877DmobwXJFrrk1/out-753-broccoli_merge_trees_full_application
vendor/moment/locale/en-sg.js in /tmp/broccoli-1877DmobwXJFrrk1/out-753-broccoli_merge_trees_full_application
Remove one of the files and re-add it with matching capitalization.
        at BroccoliMergeTrees
-~- created here: -~-
    at BroccoliMergeTrees.Plugin (/home/runner/work/bracco/bracco/node_modules/broccoli-plugin/index.js:7:31)
    at new BroccoliMergeTrees (/home/runner/work/bracco/bracco/node_modules/broccoli-merge-trees/index.js:16:10)
    at Function.BroccoliMergeTrees [as _upstreamMergeTrees] (/home/runner/work/bracco/bracco/node_modules/broccoli-merge-trees/index.js:10:53)
    at mergeTrees (/home/runner/work/bracco/bracco/node_modules/ember-cli/lib/broccoli/merge-trees.js:90:33)
    at DefaultPackager.packageTestFiles (/home/runner/work/bracco/bracco/node_modules/ember-cli/lib/broccoli/default-packager.js:1124:26)
    at DefaultPackager.packageTests (/home/runner/work/bracco/bracco/node_modules/ember-cli/lib/broccoli/default-packager.js:913:30)
    at EmberApp._legacyPackage (/home/runner/work/bracco/bracco/node_modules/ember-cli/lib/broccoli/ember-app.js:1782:46)
    at EmberApp.toTree (/home/runner/work/bracco/bracco/node_modules/ember-cli/lib/broccoli/ember-app.js:1819:27)
    at EmberApp.appInstance.toTree (/home/runner/work/bracco/bracco/node_modules/@sentry/ember/node_modules/@embroider/macros/src/ember-addon-main.js:48:35)
    at module.exports (/home/runner/work/bracco/bracco/ember-cli-build.js:51:14)
-~- (end) -~-
```

During a call with @jrhoads today, we theorised that it could be to do with the Github Actions caching of node_modules and the Yarn internal cache directory.

[These lines](https://github.com/datacite/bracco/blob/ef5dfa66fe92929fc1970c1626e67e1a2a931377/.github/workflows/deploy.yml#L29-L30) in the workflow are the cause:
```yaml
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-
```

We (sensibly) cache things that would be affected by a change in the node modules installed behind a cache key that will change when the file controlling them (yarn.lock) is modified. However - if there is a cache miss on the key, it falls back to _any_ key that begins with the `${{ runner.os }}-yarn-` name, potentially restoring an incompatible `node_modules` and yarn cache.

We confirmed that this was happening (and causing the build errors) in two ways:
1) [The logs for the failed run](https://github.com/datacite/bracco/actions/runs/4246492243/jobs/7383373167#step:6:1) clearly indicate that the restored cache comes from a different key to the one requested
```
key: Linux-yarn-9581380e5d579d8342d8e3c089e765af7d9c7862294a38becf32fcc62519458d
Cache restored from key: Linux-yarn-422a98a68b77b92dd0e5ed12fd3d12ac9cfc739562589873f2aba3b348ed48b0
```
2) Manual clearing the cache and re-running the workflow succeeded

The issue here is that the approach of restoring from a slightly different cache should not cause an issue, and I would have expected Yarn to resolve inconsistencies between node_modules versions and yarn.lock (after all, is that not it's job?) but for some reason here it clearly isn't. Possible causes could be:
* The fact that we are also caching the Yarn cache directory
* The `--frozen-lockfile` and/or `--prefer-offline` options that are passed in the workflow
* The fact that here it was technically a downgrade of packages required (due to the cache being built by the rolled-back 4.0.5 release, and the branch that failed building being forked from 4.0.4)

The logic behind it is that if you have packages A, B and C cached, and you change the version of A, but B and C remain the same, it makes sense to restore from a cache that already has B and C, and then allow Yarn to just upgrade A. This is more efficient than having to start from scratch and install A, B and C every time.

A sensible long-term fix would be to identify exactly why Yarn failed to work as expected in this situation (I am leaning towards an unholy combination of all three of the possible causes identified above plus probably some horrific secret fourth thing because javascript) but I think currently this would be a fool's errand, and so I am proposing that we go with the much simpler approach of only restoring from cache on an exact key match.

We will potentially lose some efficiency gains with the build time when updating packages, but since we tend do to this en-masse anyway and the majority of builds with the workflow  do not modify yarn.lock, I think that it is an acceptable trade-off.

**Comment by svogt0511** [comment]
I think this is a good idea.
