### ISSUE TITLE
The circle is missing from the suffix bar in Fabrica

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#778]
#### Expected Behaviour

a circle appears allowing the user to generate a new a randomly generated suffix in Fabrica

#### Current Behaviour

No circle appears

#### Steps to Reproduce

<img width="1071" alt="Screenshot 2023-08-30 at 14 43 36" src="https://github.com/datacite/datacite/assets/44582654/77eb07d5-65b3-4dac-974d-044e55d068ba">

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_479ed)

**Comment by svogt0511** [comment]
@MaryHirsch The fix for this is coming up with the Fabrica 3.24 upgrade.

**Comment by MaryHirsch** [comment]
great thanks @svogt0511 !
