### ISSUE TITLE
Metadata 4.5 - Show appropriate information in Fabrica DOI show/index pages

### ISSUE THREAD

**Issue by svogt0511** [datacite/bracco#810]
Questions for Kelly:

- [x] Does any of the information affect the display (index/show) pages?  For instance, I think the publisher name is on both of these pages.  Is there additional  info there?
- [x] The 'Export DOI Metadata' button exports publisher name to the csv file, does that stay the same?

Tasks:
- [ ] Verify that the 'Schema Version' facet in the left sidebar of the DOI index pages shows the new schema version appropriately.
- [ ] Write appropriate Cypress tests.

**Comment by kaysiz** [comment]
@KellyStathis @codycooperross @svogt0511  on this point , "Verify that the 'Schema Version' facet in the left sidebar of the DOI index pages shows the new schema version appropriately." Does it has to show the exact version or just show schema version 4?

**Comment by KellyStathis** [comment]
@kaysiz I think this must use the schemaVersion field, which contains a mix of major and minor versions.

Fro XML users (MDS API mainly), a repository could specify kernel-4.5, but it also valid tor them to specify kernel-4 (which will always reflect the latest minor version).

I think that DOIs created with the REST API also set schemaVersion to kernel-4 by default, not a specific minor version.
