### ISSUE TITLE
Selected language does not display in Language property dropdown select in Fabrica form

### ISSUE THREAD

**Issue by codycooperross** [datacite/bracco#823]
### Describe the bug

When selecting or entering a language in the Language property in the Fabrica form, the selected language is not displayed in the dropdown select. 

#### Expected Behaviour

The selected or previously entered value appears in the dropdown select. 

#### Current Behaviour

The dropdown select always displays the default instructions. 

#### Steps to Reproduce

Check the Fabrica form Language property dropdown. The other language fields—for example, for titles—do not seem to be affected.

#### Hypothesis

Checking the Ember Inspector, the data seems to be saved for Language, it's just not properly displayed. The controller behavior for the Language field is slightly different than other language fields, so there might have been a regression.

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_4noet)

**Comment by MaryHirsch** [comment]
Couldn't reproduce in stage.
