### ISSUE TITLE
Not showing title in DOI with multiple titles with multiples langaguegs

### ISSUE THREAD

**Issue by kjgarza** [datacite/bracco#83]
https://doi.datacite.org/clients/snd.snd/dois/

My suspicions is that this is related to their dois having multiple titles : <titles>
<title xml:lang="en">Swedish election study 1960</title>
<title xml:lang="sv">Svensk valundersökning 1960</title>
<title titleType="AlternativeTitle">VU60</title>
</titles> 

this is the line https://github.com/datacite/bracco/blob/master/app/templates/components/doi-list.hbs#L9

**Comment by mfenner** [comment]
@kjgarza please see https://github.com/datacite/bracco/blob/master/app/transforms/wrapped.js#L7. The bug was in line 7.
