### ISSUE TITLE
Not possible to delete a contributorType from the form 

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#836]
#### Expected Behaviour

Any information added to the the form in Fabrica can be removed if needed (unless it's mandatory and the DOI is in findable state) 

#### Current Behaviour

No delete but for contributorType, cannot be removed once added.

#### Steps to Reproduce

1. Go to Fabrica
2. Fill in the form 
3. include contributorType
4. no way to remove it once added

### Context (Environment)

Fabrica

**Comment by codycooperross** [comment]
@MaryHirsch contributorType is a mandatory attribute for contributors, so I'm confused as to why you would want to delete it unless you were going to remove the contributor entirely. Can you explain?

**Comment by MaryHirsch** [comment]
My mistake this can be closed.

**Comment by eltiffster** [comment]
Hi, I was having this issue on Chrome v.119 and 120. Just adding for reference that this issue seems related to my browser, or maybe a particular Chrome extension. I switched to Firefox and was able to save the DOI.
