### ISSUE TITLE
The test instance is referencing static files on www.stage.datacite.org

### ISSUE THREAD

**Issue by digitaldogsbody** [datacite/bracco#841]
For some reason, the version of Fabrica running on Test is trying to use some CSS etc from www.stage.datacite.org rather than assets.datacite.org (which is used in production).

Recent changes in mastino seem to have removed the DNS record for this URL, inadvertently breaking Fabrica Test.

![Screenshot at 2024-01-18 23-27-20](https://github.com/datacite/bracco/assets/93522067/a9a73098-f38e-4d94-a13c-1c73e23562ee)

**Comment by digitaldogsbody** [comment]
@svogt0511 and @bklaing2 I hope you don't mind the assignment - I figured you are probably the two people who have spent most time with Fabrica recently and so might know why it's using that resource path / how to change it.

@richardhallett mostly a flag because this seems to have been caused by the recent mastino changes

**Comment by richardhallett** [comment]
The reason it broke is due to the old staging homepage being removed by me, bracco-test was still using the old homepage for assets.
I've updated bracco-test in Vercel to use the assets server same as staging/production. This was done with Environment CDN_URL and redeploy.
