### ISSUE TITLE
The export button in Fabrica is not working

### ISSUE THREAD

**Issue by MaryHirsch** [datacite/bracco#848]
#### Expected Behaviour

Clicking "Export DOI metadata" in Fabrica exports the records on the page.

#### Current Behaviour

Clicking the "Export DOI metadata" button in Fabrica does nothing

#### Steps to Reproduce

<img width="1343" alt="Screenshot 2024-02-07 at 10 27 32" src="https://github.com/datacite/datacite/assets/44582654/445e448b-c49b-4f96-8e71-44b4b7c1cc07">

### Context (Environment)

Fabrica

#### Possible Implementation

<img src="https://front.com/assets/img/favicons/favicon-32x32.png" height="16" width="16" alt="Front logo" /> [Front conversations](https://app.frontapp.com/open/top_61p3p)

**Comment by svogt0511** [comment]
@MaryHirsch - I think that @kaysiz released a fix for this yesterday ([PR#847](https://github.com/datacite/bracco/pull/847)).  I just tried it in test and it worked for me.  Can you try this again verify whether or not it is working?

**Comment by MaryHirsch** [comment]
It's working now. Thank you!

**Comment by codycooperross** [comment]
Closing because the issue was fixed by datacite/bracco#847
