### ISSUE TITLE
Displaying DOIs for selected Prefix

### ISSUE THREAD

**Issue by shlake** [datacite/bracco#92]
From the Prefixes tab, it would be nice to click a prefix and get a listing of just those prefixes.
![screen shot 2018-07-24 at 11 44 40 am](https://user-images.githubusercontent.com/3809325/43150085-0e8440ae-8f37-11e8-92db-a83c5fda1572.png)

**Comment by mfenner** [comment]
Sherry, I like that suggestion. I think it is a good idea to list the DOIs per prefix in the DOIs tab (using a facet, see #91), and that should be integrated with the prefix tab.

**Comment by mfenner** [comment]
@shlake you can now see filtering by prefix, and linking from prefix to associated DOIs in DOI Fabrica test.
