### ISSUE TITLE
Need more ways to search DOIs

### ISSUE THREAD

**Issue by shlake** [datacite/bracco#93]
With thousands of DOIs, please let us search based on the State. I would love to facet (see) only those in "Draft" state or those of state "Findable".

another nice way to search is by prefix. Being able to just type a prefix in the search box.

**Comment by mfenner** [comment]
<img width="1331" alt="bildschirmfoto 2018-07-25 um 03 54 35" src="https://user-images.githubusercontent.com/23151/43196962-95280fbe-8fbe-11e8-97e4-2bd4ef5da864.png">

We agree, and are working on it. Searches for anything in the metadata, and facets by `state` can be tried out in the DOI Fabrica Test (https://doi.test.datacite.org). Facet by prefix is a great idea and I will add that.
