### ISSUE TITLE
Validation colors for resourceTypeGeneral missing

### ISSUE THREAD

**Issue by mfenner** [datacite/bracco#94]

**Comment by richardhallett** [comment]
This I think is referring to DOI Creation via the form, when no input is selected for the "Resource Type General" which is not optional, it should raise a validation error and colour as appropriate i.e. red.

**Comment by richardhallett** [comment]
This was a simple fix but hidden behind the fact the resourceTypeGeneral is a nested type under 'types'
The ember-cp-validation code therefore needed to be explicit for the validation test to fire accurately.
i.e. in the model for validations specify explicitly "types.resourceTypeGeneral" as opposed to just "types"
